### ISSUE TITLE
cant turn off control panel

### ISSUE THREAD

**Issue by mrmeohen** [Kalaborative/survivio-plus#10]
please put the panel in the right screen.
chect work well but the panel right centrel screen so can play

**Comment by Kalaborative** [comment]
I don't understand... could you send a screenshot link?

**Comment by mrmeohen** [comment]
https://cdn.discordapp.com/attachments/450121951432802319/475592780362678272/New_Bitmap_Image.bmp

https://cdn.discordapp.com/attachments/450121951432802319/475607417980190720/New_Bitmap_Image_2.bmp

here bro, esc and B buttons cant make panel turn off

**Comment by Kalaborative** [comment]
Try redownloading it now.

**Comment by mrmeohen** [comment]
It work very well. Thank you
