### ISSUE TITLE
keybinds dont work and autoaim doesn't work either

### ISSUE THREAD

**Issue by gblosen** [Kalaborative/survivio-plus#103]
I can't shoot with the left mouse button even though i changed it a ton of times in the keybindings. It just switches my weapons whenever i click, even when i set the keybind for switch weapons to v. Idk why it doesn't work, and its easier to play without the hack. lmk if im doing anything wrong.

**Comment by silentes** [comment]
You can reset all your bindings by deleting the "cheat2Setting" entry in your local storage. Hit F12, click the Application tab, on the left, click "Local Storage" , click "surviv.io" and delete the cheat2Setting key
