### ISSUE TITLE
Freeze after 1-3 minutes.

### ISSUE THREAD

**Issue by Akentrus** [Kalaborative/survivio-plus#107]
Hey! First of all great work thanks for continuing the project :) Second thing as the title says the game is freezing in Solo after 1-3 minutes maybe its an error on my side but i'm not sure.

Thanks for helping

best regards

I dont know what account is logged in 🥇

**Comment by IME9** [comment]
Agreed have same problem.

**Comment by IME9** [comment]
"Active resource loading counts reached to a per-frame limit while the tab is in background. Network requests will be delayed until a previous loading finishes, or the tab is foregrounded. See https://www.chromestatus.com/feature/5527160148197376 for more details" 

????

**Comment by Kalaborative** [comment]
Hey,

yeah this is occurring for me also. I'm not sure what it could be yet... For now only duo or squads work

**Comment by IME9** [comment]
Well its not like a hack is needed lol 

https://gyazo.com/e0c21ae881fbed2fdd7883e5cd28c730

I can win ez anyway

**Comment by kirillovmr** [comment]
Have the same problem after update

**Comment by sobol3d** [comment]
let`s hope that is not a test of some kind of new extention blocker

**Comment by Kalaborative** [comment]
well it's gone now so I guess this isn't an issue anymore lol
