### ISSUE TITLE
frezze (((

### ISSUE THREAD

**Issue by vipermrussia** [Kalaborative/survivio-plus#111]
![default](https://user-images.githubusercontent.com/44654976/47821193-b0b56e00-dd81-11e8-9d58-b5baa3dff892.png)
after 30-40 sec player frezze and not move
(only solo mode)

**Comment by vipermrussia** [comment]
![default](https://user-images.githubusercontent.com/44654976/47821275-f4a87300-dd81-11e8-8402-92fc1c22d26b.png)

**Comment by pilgrimoflight** [comment]
> ![default](https://user-images.githubusercontent.com/44654976/47821193-b0b56e00-dd81-11e8-9d58-b5baa3dff892.png)
> after 30-40 sec player frezze and not move
> (only solo mode)

Уже как минимум 2 треда создано до тебя.  Зачем засорять? 
И да, я уверен 99%, что тебя рака наказывал в соло=)

**Comment by vipermrussia** [comment]
> Уже как минимум 2 треда создано до тебя. Зачем засорять?
> И да, я уверен 99%, что тебя рака наказывал в соло=)

мне вообще похую на тебя, это рандомная игра, кому то везет, а кому то нет. 
а если ты здесь, значит играешь с читами, и рачище еще тот ;) без читов тебя даже младенец уделает

**Comment by silentes** [comment]
Yes dev knows now stop opening new issues
