### ISSUE TITLE
I can't close the window option

### ISSUE THREAD

**Issue by darknessbank** [Kalaborative/survivio-plus#12]
https://cdn.discordapp.com/attachments/475693696617152522/475693753395314688/unknown.png

When press ESC will this
https://cdn.discordapp.com/attachments/475693696617152522/475693818381991937/unknown.png

**Comment by Kalaborative** [comment]
It seems I can't replicate it... What browser are you using?

**Comment by darknessbank** [comment]
Sorry for late
I use Chrome

**Comment by Kalaborative** [comment]
Try redownloading it now.

**Comment by darknessbank** [comment]
**It works again Thank you bro.**
I dont like autoaim 
it can change autoaim button but.. you remove it
you can bring it back?

**Comment by Kalaborative** [comment]
Yes, that is being worked on #13

**Comment by Kalaborative** [comment]
It's been added back
