### ISSUE TITLE
Auto Reload

### ISSUE THREAD

**Issue by Drew12473** [Kalaborative/survivio-plus#121]
When you have the M220, you shoot once, then it has to reload taking away the 2 shots right after each other.  and it takes 3 seconds to reload.

**Comment by Kalaborative** [comment]
Good point, guess I hadn't noticed that because I always hold down the mouse to shoot both shots. I could remove auto reload for mp220 though

**Comment by Drew12473** [comment]
ya could you do that?  I love your hacks dude.

**Comment by Kalaborative** [comment]
Sure
