### ISSUE TITLE
Update: Squads is broken

### ISSUE THREAD

**Issue by Kalaborative** [Kalaborative/survivio-plus#124]
Yes, squads is broken (just like the Halloween update that broke Solo)

Freezing occurs after about a minute into the game

The best I can do is to compare each of the modules with the old file and find what changed, the problem is there's a lot of them.. but I think that's the best approach to fixing this 

Solo and Duo modes work fine.

Sorry for the inconvenience and hopefully it will go away soon 😭

**Comment by pilgrimoflight** [comment]
If Jesus exist, he is almost that helpful as Kalaborative)))

**Comment by ninjaman911** [comment]
Do you know when this will be fixed? Thanks for all the work you do.

**Comment by briaplaz** [comment]
I was just about to make an issue. Thanks for patching it for solo and duos.

**Comment by ninjaman911** [comment]
is it close to being fixed?

**Comment by pilgrimoflight** [comment]
Update about an hour ago, but still Squad is BROKEN(

**Comment by IME9** [comment]
more like squad always freezes

**Comment by ninjaman911** [comment]
did the guy stop trying? I dont want to get my hopes up.

**Comment by phase** [comment]
> did the guy stop trying? I dont want to get my hopes up.

He said 11 hours ago he was going to work on it.

**Comment by silentes** [comment]
Stop opening issues and adding new comments. We should know by now that it isn't working.

**Comment by ninjaman911** [comment]
is it done lmao?

**Comment by silentes** [comment]
can you wait lmao?

**Comment by Kalaborative** [comment]
keep this open so people dont make new ones lol

**Comment by ninjaman911** [comment]
> keep this open so people dont make new ones lol

Do you know how long the new desert mode will last and can you fix the freeze beforehand, or are you just gonna wait till the event is over? Thank you for everything.

**Comment by Kalaborative** [comment]
I think we'll just have to wait until it's over, usually lasts just a few days
