### ISSUE TITLE
Lags

### ISSUE THREAD

**Issue by pilgrimoflight** [Kalaborative/survivio-plus#128]
I have 100 MB connection. Pretty fast laptop. 
Still for about few weeks - i cant play normally. I got freezes every 5-10 seconds, and its ruin every game session. Ive noticed that sometimes after cheat update - everything is running fast and okay. 
But today - freezes again.  Without cheat - game is okay. 

So maybe someone has an idea what is causing these freezes?

**Comment by BopItFreak** [comment]
for some reason, the websocket connection resets, causing it to freeze. I think the hack is sending too many  packets or something
