### ISSUE TITLE
Love it! But...

### ISSUE THREAD

**Issue by reloadednfo** [Kalaborative/survivio-plus#15]
Thank you for bringing this cheat back from the grave! I always preferred it over the other one, and it looks like most everything is fixed. I'm also happy its working in Opera as well.

The only thing I think should be changed is removing the radio. I just don't really see the point of it. If someone wants to listen to music, they can open up their own music or something, this just adds lag to the cheat for a feature that's not relevant to the game and it's kinda annoying.

Also, although everything seems to be working, I do notice an error in Opera. Not sure how much you know about Opera development (it's the same base as Chrome) but I'll post the error anyways
![capture](https://user-images.githubusercontent.com/40761130/43990298-04c954d8-9d0f-11e8-8f52-65216a15d907.PNG)

One small suggestion as well: A button that quickswitches between juts the two weapons. The other cheat has this and it's super helpful. Maybe put it as an optional keybind or something, but it would allow you, no matter what your holding, to just switch between the 1 and 2 slots, instead of the regular quickswitch which brings you back to your last slot.

Anyways, thanks again!

**Comment by Kalaborative** [comment]
Thanks so much for the feedback! I'm not sure, for me the radio doesn't lag my game. I just took the idea from another extension and many people seem to like it, though I'm always open to adding more. 

The warning is coming from the synchronous request instead of using asynchronous (or AJAX), I could change it to async, but there's a chance something else won't work. 

The quickswitch was mentioned before and is definitely going to be worked on! 

Cheers~

**Comment by silentes** [comment]
@Kalaborative After the quickswitch gets implemented, maybe consider a double pump script that when executed, shoots one gun, switches to the next, shoots, and switches back to the original gun. I dont know if this is possible but it would be kinda helpful, thanks.

**Comment by Kalaborative** [comment]
@silentes not sure if the second part is necessary, I mean it's doable, but idk how many people would really use it lol.

**Comment by Kalaborative** [comment]
Yeah, tried doing the whole auto switch and shoot thing, it just kept shooting indefinitely lol. Maybe I'll return to that idea later tho. 

Switching `false` to `true` does get rid of the warning, but the text on the left when you load the game doesn't load when `true`. So for now, I think it would be okay to keep synchronous for now. 

Thanks!
