### ISSUE TITLE
Hack Not Working Please Fix ASAP

### ISSUE THREAD

**Issue by techgib** [Kalaborative/survivio-plus#153]
Hack stops working, able to join game but aimbot, transparency, laser and auto switch gun does not work

**Comment by DatBoiBaku** [comment]
aimbot - works but no laser
transparency - yeap

**Comment by MisfitRanch101** [comment]
everything but aimbot nearest player laser and transparency appears to work

**Comment by MisfitRanch101** [comment]
I screenshotted the errors
![error 1](https://user-images.githubusercontent.com/39129480/48971854-8e63e880-efed-11e8-836c-152109130f0c.PNG)
![error 2](https://user-images.githubusercontent.com/39129480/48971855-8e63e880-efed-11e8-99d4-174ba986890d.PNG)
![error 3](https://user-images.githubusercontent.com/39129480/48971856-8e63e880-efed-11e8-986c-897989f75fba.PNG)


 if this helps somehow
