### ISSUE TITLE
Minorish Bugs

### ISSUE THREAD

**Issue by 7774Bob** [Kalaborative/survivio-plus#154]
3 things: 
One, keybindings for mice do not work when the work w/out the hack
Two, it uses bandages when I left click and none of my key bindings for bandages (w/ or w/out the hack) is left click
Three, please make it specific what keybinds are for the meds. there is a first aid kit and a medkit and I don't know what the difference is. Also, there what is the stimulator.

**Comment by silentes** [comment]
The first aid kit is the pills and the stimulator is the med kit dumbass

**Comment by silentes** [comment]
Well maybe if u weren't autistic, u would be able to play the game without binding bandages to lmb

**Comment by silentes** [comment]
better shut yo ass up before I block u from this extension
