### ISSUE TITLE
GUI/Switching Guns?

### ISSUE THREAD

**Issue by David-Rodden** [Kalaborative/survivio-plus#156]
Can't find a concise explanation on how to toggle certain functions such as transparency, among other things. Also, is there a key that allows for switching guns/removing guns?

**Comment by silentes** [comment]
Check the menu

**Comment by David-Rodden** [comment]
I don't see any menu or how to access it, all that is displayed is the radio feature on the start screen

**Comment by Slip1244** [comment]
esc dumbass

**Comment by David-Rodden** [comment]
> esc dumbass

sure, within the game, you absolute mongoloid

**Comment by Slip1244** [comment]
what's wrong with configuring in game?
