### ISSUE TITLE
Hack downloaded but not working

### ISSUE THREAD

**Issue by dannyyyhan** [Kalaborative/survivio-plus#159]
![image](https://user-images.githubusercontent.com/45378987/49056775-b22c5780-f1c2-11e8-8bf9-55a992cef4e0.png)

I keep on redownloading the hack but everytime I open surviv.io it says I need to update it and I do. Also I get the mini window that says that I downloaded the hack so I'm very confused.

**Comment by Kalaborative** [comment]
it works fine for me. if it's saying you need to update, make sure you've deleted older versions of the hack and verify you're on the latest version.
