### ISSUE TITLE
Hack patched

### ISSUE THREAD

**Issue by silentes** [Kalaborative/survivio-plus#16]
They also added a new menu for key mappings
![1](https://user-images.githubusercontent.com/42192427/44071260-b32df8be-9fba-11e8-9932-257852b02f9e.png)

**Comment by humphreygaming** [comment]
yes, he is updating it

**Comment by humphreygaming** [comment]
or not, maybe tomorrow

**Comment by Kalaborative** [comment]
I'm working on it as of right now... I'm afraid it's more than just a simple deobfuscation procedure. The whole "bind to anything you want" thing has changed everything and there's no longer a "mousePressed" variable. I'm trying my best.

In the meantime, transparency and enemy lines work fine!

**Comment by humphreygaming** [comment]
k

**Comment by humphreygaming** [comment]
so no autoaim?

**Comment by Kalaborative** [comment]
Nope

**Comment by Kalaborative** [comment]
It will look like it, but you're not actually doing auto aim
