### ISSUE TITLE
Error Image Upload, hack not working(duh)

### ISSUE THREAD

**Issue by MisfitRanch101** [Kalaborative/survivio-plus#173]
![surviv io error 1](https://user-images.githubusercontent.com/39129480/49624316-ef50d080-f99e-11e8-9f51-74d4ccdd0da5.PNG)
![surviv io error 2](https://user-images.githubusercontent.com/39129480/49624317-ef50d080-f99e-11e8-83d8-80ed8352f254.PNG)
Error Images, hope this is slightly helpful

**Comment by reflexin** [comment]
@silentes Why are you closing all of these issues? This could actually be helpful.
