### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by yusefmian** [Kalaborative/survivio-plus#174]
Uh, I don't know why my issue was closed, the hack is still broken and the game has been patched.  

Please keep this open

**Comment by silentes** [comment]
we only need one issue and its below yours. Stop opening more issues or we'll ban you from this repo.

**Comment by yusefmian** [comment]
You clearly don't know what you are talking about, friend.

Below is the freeze bug, that was opened 3 days ago. The new update was released 1 day ago. It is a different bug because the entire hack stopped working, but it doesn't freeze the game.

Please actually take the time to read before closing issues wildly for no reason. It is not necessary and, frankly, it shows lack of detail.

Play surviv.io and you will see.
