### ISSUE TITLE
Stone Hammer not working...

### ISSUE THREAD

**Issue by simpleperson123** [Kalaborative/survivio-plus#178]
Hi,

Updated hacks are working fine withotut freezes and other bad effects, but when I found Stone Hammer(It's always in the hidden bunker) it's not working. I can't use it even, when I turn bumpfire off.
Can you fix this please?

Thank you.

**Comment by yarkoval** [comment]
> Hi,
> 
> Updated hacks are working fine withotut freezes and other bad effects, but when I found Stone Hammer(It's always in the hidden bunker) it's not working. I can't use it even, when I turn bumpfire off.
> Can you fix this please?
> 
> Thank you.

hi there) i suppose   it's not working cause Stone Hammer isn't  in autoFireGuns list. If you doesn't want to wait you can fix it  yourself by adding it manually in file gameUpdate.js ( this file is in folder  "payload" ) . After you add it in list, save changes and install unpacked extension as usual. 

 i did the same when  they added M1100 shotgun  and it helped me before  Drew fixed it here.
![screenshot_1](https://user-images.githubusercontent.com/14039808/49669876-a5c5bb80-fa5a-11e8-8cc6-07879ecb77ac.jpg)

**Comment by simpleperson123** [comment]
But what's the name of the Stone Hammer? i tried stone_hammer, but it's not working...
