### ISSUE TITLE
Some things are not working...

### ISSUE THREAD

**Issue by MonsterPlays** [Kalaborative/survivio-plus#19]
Hi there, 

I downloaded the hack again, but I have a few things that dont work. I can't scroll through my weapons anymore, I cant click 1,2,3 or 4 to go through my weapons. The only thing that works to scroll to weapons is either click them or use the , but then i cant equip my melee or grenades..

Is this a glitch or do I have to download the hack again?

Sincerely,

Monster

**Comment by MonsterPlays** [comment]
Everything works fine now, except for the grenade timer. The grenade timer starts when u just equip grenades and not holding it yet...

**Comment by MonsterPlays** [comment]
Now i played another game and it did the same as i said in my first comment

**Comment by silentes** [comment]
@Kalaborative good job man

**Comment by silentes** [comment]
@MonsterPlays Dude the commands that you use in game are the ones you preconfigured in the hack menu, not the game menu. So if u want to use 1234 for weapons u have to bind them yourself in the HACK MENU.

**Comment by silentes** [comment]
@Kalaborative I cant switch to any weapons using binds after the first game of playing. The first game was fine but the next game I couldn't do any of that. I tried reloading and rebinding, but the only solution is to reinstall every time.

**Comment by Kalaborative** [comment]
Strange. I'll try to reproduce that and see what's wrong. Thanks

**Comment by Kalaborative** [comment]
Yeah, some reason after the first game I can't move at all. yet I can still use fists or do emotes. Kind of stumped why this is happening only after the first game...

**Comment by mi99cool** [comment]
I too have the problem after first game u get stuck, currently I only refresh the surviv website and it works, You have to do that refresh the page each time to play the game, @silentes u don't need to reinstall every time.

**Comment by Kalaborative** [comment]
I can confirm the same. I only needed to refresh the game for it to work
again. Hopefully I'll figure it out

**Comment by mi99cool** [comment]
@Kalaborative nice work on the extension, will you be adding the bump fire on that?

**Comment by humphreygaming** [comment]
here is the bumpfire code @Kalaborative window.autoFire = function(obfuscate, game, variables) {

	var items = variables.items;
	var binded = false;
	var autoFire = false;
	var singleFireGuns = [];

	if(!!!items) {
		console.log("Cannot init autoFire");
		return;
	}

	var getWeaponsByType = function(type) {
		var weaponsList = [];
		var _items = Object.keys(items)

 		for(let i of _items) {
 			let item = items[i];
			if(item.type === type) {
				weaponsList.push(i);
			}
		}
		return weaponsList;
	}

	var getWeaponsByFireMode = function(fireMode) {
		var weaponsList = [];
		var _items = Object.keys(items)

 		for(let i of _items) {
 			let item = items[i];
			if(item.fireMode === fireMode) {
				weaponsList.push(i);
			}
		}
		return weaponsList;
	}

	var updateState = function() {
		var curPlayer = game.scope[obfuscate.activePlayer];
		var mouseButtons = game.scope[obfuscate.input.main][obfuscate.input.input].mouseButtons;

		if(mouseButtons[0] &&
			singleFireGuns.includes(curPlayer.weapType)) {
			autoFire = true;
		} else  {
			autoFire = false;
		}

		if(binded) {
			setTimeout(updateState);
		}
	}

	var defaultInputMousePressedBaseFunction = function(e) {};

	var bind = function() {
		var w1 = getWeaponsByFireMode("single");
		var w2 = getWeaponsByType("melee");
		singleFireGuns = w1.concat(w2, "fists");

		defaultInputMousePressedBaseFunction = game.scope[obfuscate.input.main][obfuscate.input.input][obfuscate.input.mousePressed];
		game.scope[obfuscate.input.main][obfuscate.input.input][obfuscate.input.mousePressed] = function(e) {
			if(autoFire)return true;

			return defaultInputMousePressedBaseFunction.call(game.scope[obfuscate.input.main][obfuscate.input.input], e);
		};

		setTimeout(function() {
			updateState();
		});

		binded = true;
	}

	var unbind = function() {
		binded = false;

		defaultInputMousePressedBaseFunction = function(e) {
            return !this.mouseButtonsOld[e] && !!this.mouseButtons[e]
        };
        game.scope[obfuscate.input.main][obfuscate.input.input][obfuscate.input.mousePressed] = defaultInputMousePressedBaseFunction;
	}

	var isBinded = function() {
		return binded;
	}

	return {
		bind: bind,
		unbind: unbind,
		isBinded: isBinded
	}
}

**Comment by Kalaborative** [comment]
Let me know if you can still play with game restarts.

**Comment by mi99cool** [comment]
Hi, Yes I can confirm that I can still play when the new game starts and the movement and everything is working. You have fixed the restart bug, Thanks

**Comment by Kalaborative** [comment]
Awesome. 😄 I will work on the grenades tomorrow. Cheers!
