### ISSUE TITLE
FOR ALL OF YOU WHO ARE EXPERIENCING ISSUES READ THIS!!!!

### ISSUE THREAD

**Issue by TheSatanicAngeI** [Kalaborative/survivio-plus#191]
### Hacking is pretty much over now.

> Assumptions

1. Since newest update of the game, hacks are broken due to unknown changes.

2. Since newest update of the game, devs decided to forbid hacking and implemented a detection more performant than the last one resulting in closing websocket upon suspicious data transfert or so with the local user (causing the game to still run but ur visual stop responding)

3. Visual glitch occuring due to code not being deobfuscate (see PowerOfUniverse claim to have fixed it but only selling it not giving it)

**Comment by humphreygaming** [comment]
obviously you have not studied the surviv code and seen its structure, or you are just saying random shit at this point. Hacks are not over

**Comment by sobol3d** [comment]
About selling the hack, why buing something that will not work just in next update. (a few days i think) 
powerofunverse did not put any prof that his hack is working, one screen with score that you can get before game stops, 
second thing and im sorry to say that as i im form Poland myslef, that what he is doing is tipical for some part of Polish people who are not grow enough to share the good ionsteed of only seling it.
