### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hairflip** [Kalaborative/survivio-plus#194]
not working as of 12/12/2018
except for sometimes the radio works

**Comment by yarkoval** [comment]
hi) what exactly doesn't work?
I don't listen radio,  but everything else is fine for me now.

**Comment by hairflip** [comment]
how do you enable developer mode on windows plz help me

**Comment by yarkoval** [comment]
@hairflip windows?  Maybe you mean browser?

**Comment by silentes** [comment]
@hairflip https://www.youtube.com/watch?v=2iwKaTEeti4

**Comment by hairflip** [comment]
it says mainifest file is missing what do i do
