### ISSUE TITLE
the new update

### ISSUE THREAD

**Issue by loserwear** [Kalaborative/survivio-plus#198]
when the hack is enabled when i go into a game it just shows me green and i cant do no nothing

**Comment by yarkoval** [comment]
Yeah, have same problem. It caused by todays update. Please be patient and just wait.

**Comment by Tarun430** [comment]
I have the problem too

**Comment by survivhacker** [comment]
Hopefully, this will be fixed its caused by the new update it should be fixed when the update goes away or by the end of the day.

**Comment by survivhacker** [comment]
its not fixed
