### ISSUE TITLE
About current release

### ISSUE THREAD

**Issue by Kalaborative** [Kalaborative/survivio-plus#20]
Grenades, for some reason, are currently unusable, this happens for both smoke and frag grenades. Everything else *should* work. 

Thanks, and will work on it some more.

**Comment by mi99cool** [comment]
@Kalaborative Hi there, just wanted to let you know if your not aware the Mosin-Nagant also does not seem to fire and is not working. I would assume maybe all the snipe weapons such as SV-98 and AWM-S dont work but cant confirm as i only got my hands on the Mosin-Nagant.

**Comment by Kalaborative** [comment]
It just so happens to be if it's not in the `autoFireGuns` array, it won't work at all... That's why frags also don't work. So I added them (and smoke) so theoretically all weapons have bump fire. You can still hold down the mouse for frags as well, so that shouldn't be a problem now. 

This was just a monkey patch, because if you turn bump fire off, you wont be able to click. So still not *completely* there, but if you have it on you won't notice the difference.
