### ISSUE TITLE
0.18.2 Scroll wheel to change weapons doesn't work

### ISSUE THREAD

**Issue by robertkent87** [Kalaborative/survivio-plus#21]
I've found that often I can't change weapons with the scroll wheel

**Comment by Kalaborative** [comment]
Scroll wheel is reserved for zoom function. If you want to switch weapons you could use the number keys or the quick switch toggle, by default is the comma key

**Comment by Kalaborative** [comment]
I might be able to put scroll wheel back if zoom feature isn't on

**Comment by robertkent87** [comment]
I've rebound scroll wheel to change weapons. It works sometimes but I just played a round where the frist (and only) weapon I picked up was M416 and I couldn't change back to fists

**Comment by Kalaborative** [comment]
Scroll wheel will work normally if you have zoom feature disabled. If you had zoom enabled and you want scroll wheel functionality back, you might have to restart the game for it to take effect. Should make that easier so you don't have to bind weapon changing to scroll wheel.

This also means if you have zoom disabled, you can use both the scroll wheel **and** the quick switch toggle to change weapons.
