### ISSUE TITLE
Hack not working...

### ISSUE THREAD

**Issue by simpleperson123** [Kalaborative/survivio-plus#212]
When I join to game, no hacks are working, but the game is not freezing :D. I got the latest version.

**Comment by STG315** [comment]
request.open('GET', chrome.extension.getURL(fileName), false); Browser see this like a problem

**Comment by survivhacker** [comment]
var gameInitBase = mainModule.prototype[obfuscate.init];

is an error i guess

**Comment by Kalaborative** [comment]
yeah it's been fixed, just redownload and you should be good to go
