### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by Brushfiremage62** [Kalaborative/survivio-plus#215]
request.open('GET', chrome.extension.getURL(fileName), false);
start.js:18 (loadFile)
![screenshot 2018-12-18 at 2 33 47  #pm](https://user-images.githubusercontent.com/45979888/50181420-f4344f00-02d1-11e9-9da3-e8c59e66c98c.png)

**Comment by simpleperson123** [comment]
I got the same error too. In console, I have a warning with some XML request, but the hacks are working perfectly without freezing. :-)

**Comment by DuckerMan** [comment]
Does not work for me

**Comment by silentes** [comment]
yes it is being fixed atm, please be patient

**Comment by silentes** [comment]
no its not
