### ISSUE TITLE
bullets disappear

### ISSUE THREAD

**Issue by Brushfiremage62** [Kalaborative/survivio-plus#218]
sometimes late in the game i die because my long range (like lets say ak) bullets don't come out of the gun causing me to lose
![screenshot 2018-12-19 at 8 59 01 am](https://user-images.githubusercontent.com/45979888/50227978-99036a80-036c-11e9-9e34-5a6c82eee6eb.png)

**Comment by survivhacker** [comment]
that does not happen to me

**Comment by silentes** [comment]
you have to click left mouse to shoot
