### ISSUE TITLE
we need another keybind 

### ISSUE THREAD

**Issue by Brushfiremage62** [Kalaborative/survivio-plus#219]
to be able to scroll to change your weapons and plus switching with aimbot on needs to be a little bit smoother and fast especially with duos and squads

**Comment by silentes** [comment]
wtf is switching with aimbot on

+

you can bind scroll wheel to next slot...

**Comment by Brushfiremage62** [comment]
but only one way, lets say i wanted to bind scroll wheel up and down, i can only do one or the other
    On Wednesday, December 19, 2018, 1:14:23 PM CST, silentes <notifications@github.com> wrote:  
 
 
Closed #219.
