### ISSUE TITLE
Scroll still not working...

### ISSUE THREAD

**Issue by MonsterPlays** [Kalaborative/survivio-plus#22]
Hi there,
When I played my first game the scroll and everything worked fine, but the second game I couldn't scroll through my weapons any more... I already re-downloaded the hack, but it is still not working after a second game.

Could u please fix this, because scrolling through my weapons is pretty important 😞 

Sincerely,

Monster

**Comment by Kalaborative** [comment]
Scroll is still working for me, for the first game and every game afterwards. 

Are you using the zoom feature?

**Comment by MonsterPlays** [comment]
I use my scroll to go through my weapons; down is next weapon, up is previous weapons. To zoom I use [ and ]...

**Comment by Kalaborative** [comment]
Try setting the binds to something else, I'm guessing it's conflicting with the game

**Comment by Kalaborative** [comment]
Zooming should always be set to the scroll wheel... Idk how you've got them bound to [ and ] keys... 🤔

**Comment by mi99cool** [comment]
Hi, It could be that you need to restore the new keybind features that surviv added to default they where conflicted with this extension keybinds. I restored them to default and now all is working as it should.

**Comment by MonsterPlays** [comment]
In the menu in ESC. In the key binding stuff I made zooming in to [ and zooming out to ], then I changed the next weapon to scroll down and previous to scroll up

**Comment by silentes** [comment]
@MonsterPlays The problem is you're using scroll to change weapons. Why? Using keys would be your solution. How can you quickswitch easily?

**Comment by MonsterPlays** [comment]
I prefer to use it like u do in normal surviv.io, I already tried it with some keys, but that glitched the hell out

**Comment by mi99cool** [comment]
I dont know how you getting this issue, it works fine for me

**Comment by Kalaborative** [comment]
Try resetting your preferences. Hit **F12**, go to **Application** tab, highlight the line **cheat2Setting** and hit the delete button (the X) , and refresh.

**Comment by MonsterPlays** [comment]
I did this and I rebind my next weapon keys to scroll down and up again, but it still won't work after a second game? Please fix this :c

**Comment by Kalaborative** [comment]
Do not rebind them to scroll keys, the scroll keys will change to weapons like the original game.

**Comment by MonsterPlays** [comment]
That's exactly what my issue is, why can't I bind them to those?

**Comment by MonsterPlays** [comment]
I would like to have that, before the new update it was all good, but now it doesn't work anymore :/

**Comment by Kalaborative** [comment]
It will overwrite the zoom functionality

**Comment by MonsterPlays** [comment]
I bind the zoom keys to [ and ], you really can't fix this, because it's important for me to use this, because with other keys the thing glitches all the time :C
