### ISSUE TITLE
Can't use ZQ to move

### ISSUE THREAD

**Issue by survivplususer** [Kalaborative/survivio-plus#221]
I actually don't know if it's a glitch or something but i can't move up or left.. Right and Down are working perfectly but i just can't make the up and left feature to work, which makes me blocked with going down or right.. 
![image](https://user-images.githubusercontent.com/46029056/50295516-7b232c00-0478-11e9-9833-cf6f9e473879.png)

**Comment by survivplususer** [comment]
I found out how to use Q but it's weird as fuck tho i need to use "Equip Last" to move to left

**Comment by silentes** [comment]
what is wrong with you
