### ISSUE TITLE
recommended

### ISSUE THREAD

**Issue by Brushfiremage62** [Kalaborative/survivio-plus#222]
I think it would be cool if you make where we could see the hp of the enemy like the old mod that used to be in the chrome web store. It would help alot.

**Comment by silentes** [comment]
im not even sure if this is even possible

**Comment by Brushfiremage62** [comment]
@silentes you never know until you try and also, i know its possible because on was on the extension that used to be in the chrome web store before it got taken down

**Comment by silentes** [comment]
first off, shut up. Second of all, ask the devs for the part where you get other player's health sent to your game and say its for research purposes
