### ISSUE TITLE
recommended... 

### ISSUE THREAD

**Issue by Brushfiremage62** [Kalaborative/survivio-plus#226]
I think that maybe adding auto heal or/and auto dodge would be really cool

**Comment by pilgrimoflight** [comment]
IMPORTANT : (!!!)


1. Auto loot weapon switches problem ( Got 2 powerful weapon , shoot is in low range - and cheat decides to  take a pistol! Sh!t) .

 Really, it will be very useful.

 Im begging ( if its possible) to add option  ONLY for ammo and supply autoloot,  OR to stop weapon autoloot, when   2 weapons are already handed. Its not a problem to change one weapon for better by hand during session. But BIG problem, when you are involved in shooting and weapon suddenly changed and always for worse (and reload ofcourse) Its Death 99 % 
2.  Game crashes , when smoke is released. Extinguisher in police station expecially.

**Comment by wowthisiscool** [comment]
also, prepare for a upcoming patch https://cdn.discordapp.com/attachments/480975272686911488/526193509493899294/uhoh.JPG

**Comment by theunleet** [comment]
@wowthisiscool They already implement it on zbot473's hack. Whole reason of that picture.

**Comment by silentes** [comment]
Yes the auto loot has been a problem but the easy fix is to just use fists when you loot, not that hard

**Comment by pilgrimoflight** [comment]
> Yes the auto loot has been a problem but the easy fix is to just use fists when you loot, not that hard

Do you have problems analysing my message?)

 When shooting is in bunker or whatever place, where are tons of loot from dead players - auto loot changes the weapon you are shooting in the moment - and its a problem.  More often it works exactly in battle ,but not when you just loot some stuff=)

**Comment by silentes** [comment]
yes i do have problem analysing your message, are you racist?

IMPORTANT : (!!!)

Auto loot weapon switches problem ( Got 2 powerful weapon , shoot is in low range - and cheat decides to take a pistol! Sh!t) .
Really, it will be very useful.

Im begging ( if its possible) to add option ONLY for ammo and supply autoloot, OR to stop weapon autoloot, when 2 weapons are already handed. Its not a problem to change one weapon for better by hand during session. But BIG problem, when you are involved in shooting and weapon suddenly changed and always for worse (and reload ofcourse) Its Death 99 %
