### ISSUE TITLE
Newest download of survivio+ detected

### ISSUE THREAD

**Issue by Kreijstal** [Kalaborative/survivio-plus#229]
Just tried the newest version and I got this
![image](https://user-images.githubusercontent.com/2415206/50460478-e0928380-0976-11e9-991a-50d3b4aecec8.png)
 yay and it denies websocket requests now
![image](https://user-images.githubusercontent.com/2415206/50460498-13d51280-0977-11e9-87ab-415f7d6a8275.png)

**Comment by silentes** [comment]
you've gotta be fully retarded
