### ISSUE TITLE
Autoaim issue

### ISSUE THREAD

**Issue by Composter** [Kalaborative/survivio-plus#23]
When more that one enemy around me autoaim locks on one enemy and I have no chance to aim on another enemy

**Comment by mi99cool** [comment]
You can always move the mouse cursor towards the person you want to shoot and it locks on that person. You have to at least move the cursor autoaim is helpful but you yourself have to try to aim the cursor towards the person you want to shoot

**Comment by Kalaborative** [comment]
If you have auto aim restriction disabled, it will always aim to the closest person to you. Turn it on, and it will aim closest to your cursor position
