### ISSUE TITLE
still doesnt work even after the update

### ISSUE THREAD

**Issue by slipslipslip** [Kalaborative/survivio-plus#241]

**Comment by slipslipslip** [comment]
still doesnt work even after the update

**Comment by slipslipslip** [comment]
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by silentes** [comment]
"sTiLl dOeSnT WoRk eVeN AfTeR ThE UpDaTe" 
![screenshot 104](https://user-images.githubusercontent.com/42192427/51004545-2881e080-1509-11e9-9bf3-22b1ef566936.png)
