### ISSUE TITLE
Doesnt work... It used to work yesterday but not today...

### ISSUE THREAD

**Issue by dave289** [Kalaborative/survivio-plus#242]

**Comment by dave289** [comment]
also is there a way to add unlimited health

**Comment by silentes** [comment]
"dOeSnT WoRk... It uSeD To wOrK YeStErDaY BuT NoT ToDaY..."
![screenshot 104](https://user-images.githubusercontent.com/42192427/51004572-3fc0ce00-1509-11e9-9273-22cce2d5572b.png)
"aLsO Is tHeRe a wAy tO AdD UnLiMiTeD HeAlTh"
