### ISSUE TITLE
Hack stopped completely working

### ISSUE THREAD

**Issue by simpleperson123** [Kalaborative/survivio-plus#247]
Screenshot:

<img width="959" alt="error" src="https://user-images.githubusercontent.com/45456776/51047161-22066e00-15c8-11e9-8981-ebbbf1a27f06.PNG">

**Comment by Trollfocero** [comment]
Same

**Comment by StabbyAlbert** [comment]
Yea bro, sucks

**Comment by PowerOfFusion** [comment]
If you want, I can provide a working cheat to PowerOfUniverse.

**Comment by silentes** [comment]
lmao

**Comment by PowerOfFusion** [comment]
At least it works and there are no freezes. And you can not even fix it, greetings.

**Comment by silentes** [comment]
no one asked.

**Comment by slipslipslip** [comment]
same

**Comment by STG315** [comment]
Isnt work :(

**Comment by Kalaborative** [comment]
vars updated and fixed the unauthorized extension bug, don't know about freezes but so far it's ok
