### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by simpleperson123** [Kalaborative/survivio-plus#257]
The hack now works okay, but it's freezing if you have turned on graphical features like wallhack, enemy lines, lasersight. Solution is: If game freezes, turn off all graphical features and leave only bumpfire, autoaim and autoloot on. Reload the page and play a new game, then after some time turn graphical features on again.

**Comment by XxanimeboyxXYT** [comment]
Not working

**Comment by simpleperson123** [comment]
It works for me fine now

**Comment by drogga** [comment]
I used Zbot473's hack, which also occasionally froze, until it was put on ice three days ago and AFAIK the hack detection is only active during events, e.g. Woods mode, Winter, Halloween, Desert, etc. If no events were ongoing, the hacks never freezed.

**Comment by slipslipslip** [comment]
it still freezes for me even with the things turned off
