### ISSUE TITLE
Surviv Devs are getting smarter. So lets outsmart them and kick their ass

### ISSUE THREAD

**Issue by staticoblivion** [Kalaborative/survivio-plus#263]
Hack needs update. If someone enters game with an extension to modify the game, it will say "Unauthorized extension use detected". Yeah because some idiots are too retarded to keep the hack a secret from the devs... I think he posted it on Youtube. Also a reminder: if u use the hack, SHUT UR DAMN MOUTH. At first we went undetected, now we gotta battle the devs.

**Comment by silentes** [comment]
A) The hack works dummy.
B) 'secret'. Haha.
![](https://media.discordapp.net/attachments/522890483257573376/526466769112793091/uhoh.JPG)
![screenshot 118](https://user-images.githubusercontent.com/42192427/51115746-2654a600-17d7-11e9-9e2e-abafa184967c.png)
I wonder how you can find surviv.io hacks....

C) What contribution have you made towards using this hack that you get to call this 'we'?
Is the hack supposed to be open source so you can complain?

D) "Surviv Devs are getting smarter. So lets outsmart them and kick their ass #263"
