### ISSUE TITLE
WT...

### ISSUE THREAD

**Issue by hank10322** [Kalaborative/survivio-plus#265]
![default](https://user-images.githubusercontent.com/45732841/51124984-8fc9c880-185a-11e9-8ed7-c4917691cb01.png)

**Comment by ziboy168** [comment]
https://www.youtube.com/watch?v=pEEa6b3oXjA
try it!

**Comment by ziboy168** [comment]
I have the same problem , but i can not set it . 
![image](https://user-images.githubusercontent.com/46684272/51126616-90645e00-185e-11e9-9ba5-ad022e5722e6.png)

**Comment by hank10322** [comment]
Me to

**Comment by onyGOD** [comment]
Does anyone know how to fix on mac

**Comment by silentes** [comment]
Fix: https://www.youtube.com/watch?v=pEEa6b3oXjA
