### ISSUE TITLE
Hacks not working at all

### ISSUE THREAD

**Issue by survivplususer** [Kalaborative/survivio-plus#266]
I got the radio in game but i can't use hacks.
Here is a pic of the error i'm getting. (I downloaded all the new files)

![image](https://user-images.githubusercontent.com/46029056/51131689-ba9f2700-1830-11e9-945f-09b750ad94ce.png)

**Comment by survivplususer** [comment]
new*

**Comment by silentes** [comment]
Fix: https://www.youtube.com/watch?v=pEEa6b3oXjA

**Comment by survivplususer** [comment]
The problem is that i don't have "Unauthorized extension use detected"

**Comment by silentes** [comment]
Did u download the new version?

**Comment by survivplususer** [comment]
Yes i did

**Comment by survivplususer** [comment]
Sorry for the late answer i wasn't watching GitHub
