### ISSUE TITLE
The update for read me

### ISSUE THREAD

**Issue by Brushfiremage62** [Kalaborative/survivio-plus#267]
I read the read me you updated and did everything in the youtube video but the hack still does not work

**Comment by silentes** [comment]
Fix: https://www.youtube.com/watch?v=pEEa6b3oXjA

**Comment by BopItFreak** [comment]
why can't i have clear ceiling

**Comment by mi99cool** [comment]
you cant have that maybe becuz thats how surviv can tell that the extension is being used.
