### ISSUE TITLE
KEYBINDS

### ISSUE THREAD

**Issue by WVVEY** [Kalaborative/survivio-plus#268]
Plz help with my keybinds. I usually use thumb mouse button 1 to switch guns but i know that does not work with the hack, so I want to make my right mouse button the switch guns but when i bind it, it just keeps switching guns and also i can't fist boxes. Someone plz help

**Comment by WVVEY** [comment]
Also i saw in past issue post the "cheat2Setting" thingy? But i am on a chromebook so I don't know where to do that. Someone plz walk me through this.

**Comment by silentes** [comment]
follow this video https://www.youtube.com/watch?v=pEEa6b3oXjA&

Delete all of cheat2setting to fix your problem.

**Comment by WVVEY** [comment]
Ok i fixed the unauthorized extension stuff but now i need help with the keybind stuff cause i cant fist and when i try to shoot it just keeps quick switching back and forth.
