### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by swagskillsup** [Kalaborative/survivio-plus#27]
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
5[Intervention] Slow network is detected. See <URL> for more details. Fallback font will be used while loading: <URL>
app.3b0c1882.js:1 The Web Audio autoplay policy will be re-enabled in Chrome 70 (October 2018). Please check that your website is compatible with it. https://goo.gl/7K7WLu
e @ app.3b0c1882.js:1
webpack_override.js:54 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.webpack_inject (webpack_override.js:54)
    at n (manifest.bd702314.js:1)
    at window.webpackJsonp (manifest.bd702314.js:1)
    at webpack_inject (webpack_override.js:47)
    at webpack_override.js:118
app.3b0c1882.js:1 Uncaught TypeError: Cannot read property 'stack' of null
    at window.onerror (app.3b0c1882.js:1)
stream;:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
app.3b0c1882.js:1 WebSocket connection to 'ws://na-sao-p1.surviv.io/ptc' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET

**Comment by Kalaborative** [comment]
Have you redownload the extension? Go to chrome://extensions in your browser and check the version, should be 0.19.0

**Comment by swagskillsup** [comment]
yes thanks, it works now
