### ISSUE TITLE
Game keep freezing

### ISSUE THREAD

**Issue by sobol3d** [Kalaborative/survivio-plus#270]
Not so often as in event mode, but still it frezes from time to time, any hints what can couse that in the code ?

**Comment by survivplususer** [comment]
Yeah i'm also freezing :(

**Comment by WVVEY** [comment]
same all other issues are resolved but the freezing

**Comment by mi99cool** [comment]
yes what is causes the freezing it happens in every game

**Comment by survivplususer** [comment]
Not every game but in like 5/6 game
