### ISSUE TITLE
FREEZING

### ISSUE THREAD

**Issue by WVVEY** [Kalaborative/survivio-plus#272]
Does anyone know when the freezing will be fixed?

**Comment by killercloudj** [comment]
it cant be fixed my guy the only way is to keep on putting out updates

**Comment by killercloudj** [comment]
i think at least

**Comment by killercloudj** [comment]
@Kalaborative  cant you take zbots and just update them to how you wanted because he has every thing that you want in

**Comment by ALEXXANDRO23** [comment]
@killercloudj you know what happened to @zbot

**Comment by killercloudj** [comment]
yeah he stopped because it was getting to big to handle so she stopped updating it and closed it and i am having a glitch i think because my gun won't shoot it will just keep on switching
