### ISSUE TITLE
Can you add 1 more proxy

### ISSUE THREAD

**Issue by ooferaa** [Kalaborative/survivio-plus#273]
A proxy site that you have not added
http://parmainitiative.com/

**Comment by ooferaa** [comment]
You closed it but no answer????

**Comment by ooferaa** [comment]
Huh?

**Comment by ooferaa** [comment]
check what?

**Comment by silentes** [comment]
How do you know it's not added

**Comment by ooferaa** [comment]
its not working on the site plus he only put stuff like thecircleisclosing.com but no parmainitiative

**Comment by ooferaa** [comment]
these are the only sites he put in
http://surviv2.io
https://surviv2.io
http://2dbattleroyale.com
https://2dbattleroyale.com
http://2dbattleroyale.org
https://2dbattleroyale.org
http://piearesquared.info
https://piearesquared.info
http://thecircleisclosing.com
https://thecircleisclosing.com

**Comment by ooferaa** [comment]
I just want it to work on http://parmainitiative.com/

**Comment by silentes** [comment]
"*://*.surviv.io/*",
  			"*://*.surviv2.io/",
  			"*://*.2dbattleroyale.com/",
  			"*://*.2dbattleroyale.org/",
  			"*://*.piearesquared.info/",
  			"*://*.thecircleisclosing.com/",
			"*://*.parmainitiative.com/",
  			"*://*.twitch.tv/popout/prismatichub/extensions/c79geyxwmp1zpas3qxbddzrtytffta/panel"

**Comment by ooferaa** [comment]
thanks

do I have to redownload?

**Comment by silentes** [comment]
it doesn't really matter, unless you rely on that site

**Comment by ooferaa** [comment]
yeh im really on that site
