### ISSUE TITLE
HELP! Can someone make an unblocked proxy for surviv? I use CHrome OS. Almost everygame is blocked at our school because the sites are classified as "Games"

### ISSUE THREAD

**Issue by Helixable** [Kalaborative/survivio-plus#275]

**Comment by silentes** [comment]
http://surviv2.io
https://surviv2.io
http://2dbattleroyale.com
https://2dbattleroyale.com
http://2dbattleroyale.org
https://2dbattleroyale.org
http://piearesquared.info
https://piearesquared.info
http://thecircleisclosing.com
https://thecircleisclosing.com
http://parmainitiative.com
https://parmainitiative.com
https://www.twitch.tv/popout/didius/extensions/c79geyxwmp1zpas3qxbddzrtytffta/panel
