### ISSUE TITLE
 Cheat menu is in the middle of the screen during the game.

### ISSUE THREAD

**Issue by Ekzarkun** [Kalaborative/survivio-plus#279]
http://prntscr.com/m8qxtk
http://prntscr.com/m8qxy6

**Comment by Ekzarkun** [comment]
![1](https://user-images.githubusercontent.com/41264159/51391479-f77e5d00-1b53-11e9-9235-d1c930fb79ed.jpg)
![default](https://user-images.githubusercontent.com/41264159/51391480-f77e5d00-1b53-11e9-944d-6f5350ccc2ba.jpg)

**Comment by Ekzarkun** [comment]
the menu does not respond to clicks and does not close

**Comment by silentes** [comment]
wtf, just delete the hack and reinstall

**Comment by Ekzarkun** [comment]
Hmm, it worked. The reason was what - in the source code instead of :false, it was ,false: . I changed the values ​​a couple of days ago, apparently wrong with the markup. Anyway, thanks for your help!

**Comment by silentes** [comment]
yeet
