### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Surviv23** [Kalaborative/survivio-plus#28]
I download the hack today, and when I try to play, there's 200-300 lag and 30 fps

**Comment by Kalaborative** [comment]
That is to be expected, many people will be playing the game thanks to the new patch, that's strictly to do with server overload. Just give it some time 😄

**Comment by BerserkerWorM** [comment]
Im having the same issue but it locks up for 5 -10 seconds. It only does this when the extension is active.  If I run survio with our it on it plays just fine and has 0 lag.

**Comment by BerserkerWorM** [comment]
Im do apologize I believe I fixed it and it was on my end,. I have like 5 other extensions running and for some reason if i disable those it runs fine so i believe one of them is some how interfering with this one. Not sure why or how but its all good now. Thank you.

**Comment by Kalaborative** [comment]
No problem! I'll try to work on it more.
