### ISSUE TITLE
Less freeze if you go to https://surviv.io

### ISSUE THREAD

**Issue by fahrennheit** [Kalaborative/survivio-plus#281]

**Comment by fahrennheit** [comment]
It seems like if you go to https://surviv.io instead of http://surviv.io or just surviv.io, you will get less freezing. On the same IP adress, I had 5 games 1 freeze with https, and 5 games 3 freezes without https.

**Comment by herbieLoaded** [comment]
works for me too. still freezes sometimes, but not as much times

**Comment by Brushfiremage62** [comment]
Freezes more for me

**Comment by BopItFreak** [comment]
what does the youtube vid say?
