### ISSUE TITLE
Hey bloody, fuck you

### ISSUE THREAD

**Issue by StabbyAlbert** [Kalaborative/survivio-plus#287]
https://www.youtube.com/watch?v=1LH0Io77vls hey bloody, I hope you are reading this. Because fuck you

**Comment by DatBoiBaku** [comment]
![image](https://user-images.githubusercontent.com/45308130/52491777-88cf7500-2bd0-11e9-9388-4ecffec98cd3.png)
LMAO WHO IS THIS SAVAGE
