### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by iNtENSEZZ** [Kalaborative/survivio-plus#295]
Freezing the game, update this f***

**Comment by iBLiSSINYT** [comment]
why don't you update it?

**Comment by iNtENSEZZ** [comment]
If you have a duty to fix the hack, why not properly? What is the use of fucking a hack that hangs every 2 minutes? Idiot!

**Comment by iBLiSSINYT** [comment]
I have a 'duty'? Are you a fucking kid? 
"What is the use of fucking a hack that hangs every 2 minutes? Idiot!"

If you don't like fucking the hack, don't fuck it then 🤷🤷🤷🤷🤷

**Comment by yarkoval** [comment]
@iNtENSEZZ  so maybe you'll be kind to fix all bugs and show us a 100% working cheat? If you think its so easy to maintain this i suppose  one idiot we have here is you.

**Comment by iNtENSEZZ** [comment]
Sorry for the curses, I'm very nervous, I fought with my girlfriend.

**Comment by iBLiSSINYT** [comment]
https://www.youtube.com/watch?v=29Ws50lRm04
