### ISSUE TITLE
Could you attempt to re-upload it to the web store?

### ISSUE THREAD

**Issue by SpiffyJUNIOR** [Kalaborative/survivio-plus#30]
I don't want to enable developer mode.
If not, is there a way to run the .js files with Tampermonkey?

**Comment by mi99cool** [comment]
I don't think there is any point to upload it to the web store as it would be quickly removed. Why don't you want to enable developer mode its not going to effect your browser negatively. Kalaborative has done a great job keeping this extension going i'm grateful.
