### ISSUE TITLE
Completely broken

### ISSUE THREAD

**Issue by StabbyAlbert** [Kalaborative/survivio-plus#313]
The hack is completely broken, I deobfuscated the variables and they completely match

**Comment by iNtENSEZZ** [comment]
Oof, We'll have to play without hacking until it's updated.

**Comment by iBLiSSINYT** [comment]
Its working tho.

**Comment by iNtENSEZZ** [comment]
We need to figure out a way to make sure the hack does not freeze while we play, otherwise it would be great!
