### ISSUE TITLE
Unauthorized extension use detected

### ISSUE THREAD

**Issue by BadDiego0** [Kalaborative/survivio-plus#32]
Hi! First of all, thanks for the hack! but I am having a problem, when trying to play a message appears saying '' Unauthorized extension use detected '' I can only play 5 seconds. I tried to play in incognito mode but still I can not play.
![captusra](https://user-images.githubusercontent.com/43284450/45579987-4d12c800-b849-11e8-8df6-a7356633e7b4.PNG)

![captusra](https://user-images.githubusercontent.com/43284450/45580001-69166980-b849-11e8-9fe0-8858043e932c.PNG)

**Comment by Kalaborative** [comment]
Possibly try using [PowerOfUniverse's extension](https://github.com/PowerOfUniverse/Surviv.io-Cheats). The reason I can't really help on this is because I'm not getting this error at all and I'm running the same game as everyone else. Until I can figure out how to replicate it myself, I'm not sure how to go about fixing it. 

Thanks!

**Comment by BadDiego0** [comment]
Same problem!
When i tried to play in NA server.

**Comment by jialeyu** [comment]
Have the same problem as well. Almost seems like there is a pattern (when joining a room) but it doesn't happen all the time.

**Comment by holidaynights** [comment]
What adblock are you using? I'm getting this same issue using v19.3 @Kalaborative

**Comment by mi99cool** [comment]
@Kalaborative are u working on a fix for this?

**Comment by NotLimitsFun** [comment]
:((

**Comment by Kalaborative** [comment]
To @BadDiego0  and everyone else, please let me know if this is still happening.

**Comment by jialeyu** [comment]
Still happening for me.

**Comment by Kalaborative** [comment]
@jialeyu what about now

**Comment by jialeyu** [comment]
Its working now yay
