### ISSUE TITLE
ESC menu won't open

### ISSUE THREAD

**Issue by tuckerritti** [Kalaborative/survivio-plus#320]
When I press esc, nothing happens. It should open the settings window, right? I am using chrome.

**Comment by humphreygaming** [comment]
@tuckerritti make sure Surviv+ is loaded correctly. You could try downloading it again and installing it correctly. And yes, ESC should open the settings window

**Comment by tuckerritti** [comment]
On a MacBook with a touch bar, the ESC key does not work. I used an external keyboard to fix this.
