### ISSUE TITLE
I have a comment

### ISSUE THREAD

**Issue by dankrick420** [Kalaborative/survivio-plus#322]
before you added peoples names as green, we didnt have an issue with freezing.. maybe that's why it's happening. Also, I'd like to have a version without bump fire, just auto aim and normal names.

**Comment by DatBoiBaku** [comment]
> Nope the Devs. have implemented freezing

which devs
the hack devs or surviv devs

**Comment by iBLiSSINYT** [comment]
the hack devs becuasz they wamt peple too freese

**Comment by Reeyaad** [comment]
LOL Without Bump fire there would be no benefit of using this cheat. Bump fire is one of the main advantages of this cheat
