### ISSUE TITLE
|ℝ𝔼𝔸𝔻 𝕋ℍ𝕀𝕊...|

### ISSUE THREAD

**Issue by RevoltZZ** [Kalaborative/survivio-plus#329]
Please do not keep creating issues for no reason, this is annoying and it is very annoying, if by chance your hack is not working if an update occurs in the game, wait until they create a patch, do not open inssues right away, Grate!

**Comment by humphreygaming** [comment]
or use another hack

**Comment by ninjaman911** [comment]
> or use another hack

is there another hack that works?
