### ISSUE TITLE
How to modify this hack for you own use?

### ISSUE THREAD

**Issue by Helixable** [Kalaborative/survivio-plus#330]
I'm new to javascript and I want to create my own surviv ABot. The thing is, I don;t know how to fix the hack if it is patched by the Surviv Devs. Can someone explain to me how this hack works? I have been using it since the it's creation and I'm a proud supporter :)

**Comment by iBLiSSINYT** [comment]
it points to the enemy

**Comment by reflexin** [comment]
Create a fork of this repository.

**Comment by iBLiSSINYT** [comment]
if the devs 'patch' the hack, it means variables were updated and basically you have to translate them to ur code, read app.js
