### ISSUE TITLE
Switching not working???

### ISSUE THREAD

**Issue by Brushfiremage62** [Kalaborative/survivio-plus#331]
Im able to switch to my number 2 gun but able to switch back to 1
My key-bind is RMB for switching and i've tried changing it and it still doesn't work

**Comment by iBLiSSINYT** [comment]
try this, dont really understand

https://www.youtube.com/watch?v=GEIyS8FseiA

**Comment by Brushfiremage62** [comment]
i cant use a keybind to switch back and forth, i can only do this once then i have to do it manually
