### ISSUE TITLE
How do I put functions for the wheel?

### ISSUE THREAD

**Issue by vroomZOOM** [Kalaborative/survivio-plus#333]
I would like to be able to switch weapons with the wheel but when I go into the settings how do I select the wheel - I tried clicking on zoom and moving the wheel, but that did not work and it only sets it to left mouse button. also, could you make it possible to be able to zoom in a little farther?  also, if I bind the rmb to change the weapons, I can get all my weapons except for fists. here's an idea - not enough space error when you try to pick stuff up - maybe hack that? thanks

**Comment by iBLiSSINYT** [comment]
the only way is to turn off zoom, click the switch weapon and scroll all the way up, it works
