### ISSUE TITLE
Enemy DIrection Suggestion

### ISSUE THREAD

**Issue by Helixable** [Kalaborative/survivio-plus#336]
What if you added a small text print that showed the approximate distance to the enemies?
Can you add a "Sniper Mode" Where it locks on to a enemy and waits until a clear shot to the player is there, then snipes the enemy. If you can't make it yourself, can you atleast tell me how to do it?

**Comment by iBLiSSINYT** [comment]
To add a "Sniper Mode" Where it locks on to a enemy and waits until a clear shot to the player is there, then snipes the enemy. Make it so that it locks on to a enemy and waits until a clear shot to the player is there, then snipes the enemy.

**Comment by Helixable** [comment]
Yea I know that, but How do I code that?
