### ISSUE TITLE
freezes when get near somone

### ISSUE THREAD

**Issue by gearhart21** [Kalaborative/survivio-plus#337]
freezes my game when i see somone

**Comment by RevoltZZ** [comment]
Mhm... Spam Ctrl+f5.
This works for me. 😄

**Comment by gearhart21** [comment]
does it action ally shoot the people with every bullet

**Comment by Brushfiremage62** [comment]
Did you turn off obstacle alpha, ceiling alpha, and smoke alpha... those cause the game to instantly
