### ISSUE TITLE
Have the developers abandoned this extension? Is it on its deathbed? [IMPORTANT]

### ISSUE THREAD

**Issue by reflexin** [Kalaborative/survivio-plus#338]
It seems that the freezing error (which happens 75% of the time), which is a quite fatal problem, is being ignored. No efforts are being made to fix the problem by anyone, and that includes the main developer.

I am not saying it's his fault because maybe he is busy, or doesn't understand the problem very well. Perhaps it has something to do with the code of the original developer (reuuke or something) that Kalab built off of. But no one has decided to invest energy into fixing this extension. So now the big question is, is this extension dead? On its deathbed?

**Comment by TheSatanicAngeI** [comment]
@reflexin  The freezing has been put out by the game developers (I assume so) since PowerOfUniverse stopped working on the extension and zbot173 (i think thats the right name) took care of it too. 
And every update they change some variables making it a pain to keep updated

**Comment by iBLiSSINYT** [comment]
wow, this is probably the most profound issue ever opened on this github. I appreciate you for your input in the development of this extension and I wish to hear more from you. People like you are the reason why lesbian dance theory is a top-paying major in the United States of America.

**Comment by reflexin** [comment]
> wow, this is probably the most profound issue ever opened on this github. I appreciate you for your input in the development of this extension and I wish to hear more from you. People like you are the reason why lesbian dance theory is a top-paying major in the United States of America.

Why are you such a sarcastic douche lol? You're incredibly unprofessional.

**Comment by iBLiSSINYT** [comment]
I wrote you a haiku:

what is the point of
opening this issue 
you fucking retard

**Comment by reflexin** [comment]
> I wrote you a haiku:
> 
> what is the point of
> opening this issue
> you fucking retard

You're a shitty and garbage developer. What are you 12?

**Comment by iBLiSSINYT** [comment]
that I agree with, 

and you're a great and amazing complainer that provides no value for anyone. Sit the fuck down and get the fuck out of this repository

**Comment by reflexin** [comment]
> that I agree with,
> 
> and you're a great and amazing complainer that provides no value for anyone. Sit the fuck down and get the fuck out of this repository

Nope, you closed this thread because you're butthurt about the truth about these developers abandoning this extension lol. You don't provide much value with your garbage, unsuccessful YouTube channel lol so stop acting so high and mighty.

**Comment by iBLiSSINYT** [comment]
> stop acting so high and mighty.

laugh 
my
ass
off 
u 
are 
a 
comedian

**Comment by reflexin** [comment]
Dumb child

**Comment by humphreygaming** [comment]
@reflexin  holy shit thats alot of hate you are giving to poor silentes

**Comment by DamienVesper** [comment]
@reflexin At least he can code unlike you.

**Comment by reflexin** [comment]
> @reflexin At least he can code unlike you.

I can code you fucking retard, lol. All he does is advertise his shitty channel on this repository.

**Comment by reflexin** [comment]
> @reflexin holy shit thats alot of hate you are giving to poor silentes

You act as if he didn't start it by being a sarcastic dickhead

**Comment by humphreygaming** [comment]
@reflexin don't mind iBLiSSIN then, he is a bit impulsive and has a  smart-ass personality but is otherwise a nice guy? (i thinks)

**Comment by iBLiSSINYT** [comment]
Wow quite a few points that are left exposed and unedited. 

Point #1: 

> You act as if he didn't start it by being a sarcastic dickhead
![image](https://user-images.githubusercontent.com/42192427/54576918-3bfd6c00-49d0-11e9-8365-f4ef12660936.png)

Point #2:

> I can code you fucking retard, lol. All he does is advertise his shitty channel on this repository.

You can code, but you are useless in this repository, therefore have significantly lower value than a developer, who actively MAINTAINS the hack so that IMMATURE FUCKS like you can win the game. Sorry this wasn't clear, but the only thing I ask is for people not to open RETARDED and USELESS issues on this repository. It logically made sense in my developed mind, but I have realized this isn't the case for ALL people.

I bet on my fucking family you are younger than me. Dare to respond, I'm done with you, buddy.

**Comment by reflexin** [comment]
> Wow quite a few points that are left exposed and unedited.
> 
> Point #1:
> 
> > You act as if he didn't start it by being a sarcastic dickhead
> > ![image](https://user-images.githubusercontent.com/42192427/54576918-3bfd6c00-49d0-11e9-8365-f4ef12660936.png)
> 
> Point #2:
> 
> > I can code you fucking retard, lol. All he does is advertise his shitty channel on this repository.
> 
> You can code, but you are useless in this repository, therefore have significantly lower value than a developer, who actively MAINTAINS the hack so that IMMATURE FUCKS like you can win the game. Sorry this wasn't clear, but the only thing I ask is for people not to open RETARDED and USELESS issues on this repository. It logically made sense in my developed mind, but I have realized this isn't the case for ALL people.
> 
> I bet on my fucking family you are younger than me. Dare to respond, I'm done with you, buddy.

And your screenshot proves what lmao? Look at your response retard.

What do you even do LMAO besides advertise your shitty channel everywhere? Your "developed" mind has only led you to hardly 300 subscribers. Get off your high horse buddy.

**Comment by TheSatanicAngeI** [comment]
@reflexin  Are you fucking retarded ? If he wasn't taking his time to help out this hack would have been long gone since @Kalaborative  stopped working on it and zbot aswell (another hack)

**Comment by TheSatanicAngeI** [comment]
Like what the fuck do you think this is retard ? 

https://gyazo.com/71ff8f67416991e51b721294fddd1d9b

A FUCKING COMMIT 


And you know what that commit did ?

FIX THE FUCKING EXTENSION

SO SHUT THE FUCK UP OR HELP IF YOU ARE SO ANNOYED BY THE FREEZING

**Comment by TheSatanicAngeI** [comment]
@reflexin  You think he gets paid for all this ?

ITS FREE DUMBASS HE DONT GET ANYTHING

THE ORIGINAL DEVELOPPERS WERE ADVERTISING A LOT THE WORD "DONATE"

SO WHY CAN'T HE JUST GET AD REVENUE ?

**Comment by TheSatanicAngeI** [comment]
@reflexin  YOU KNOW CODING YET ALL YOU DO HERE IS COMPLAINING. 

I THINK YOU DON'T KNOW WHERE YOU BELONG BUDDY.

**Comment by TheSatanicAngeI** [comment]
@reflexin  You come here open a new issue just to shit on @iBLiSSINYT  get the fuck out retard.


I'm sick of all this underseved hatred. 

Not only againts  @iBLiSSINYT like it affect me too even if I'm not implicated.

So much negativity is bad for you.

**Comment by TheSatanicAngeI** [comment]
@reflexin  ALSO YOU ACT AS IF YOU WERE INNOCENT JUST READ YOUR FUCKING ISSUE TITLE "Have the developers abandoned this extension? Is it on its deathbed? [IMPORTANT]"

> It seems that the freezing error (which happens 75% of the time), which is a quite fatal problem, is being ignored. No efforts are being made to fix the problem by anyone, and that includes the main developer.

YES IT IS BEING ABANDONED AND YOU KNOW WHY ?

**ITS A PAIN TO KEEP UPDATED WITH ALL THE SHITTY KIDS AROUND LIKE YOU THAT OPEN 999 ISSUES JUST TO COMPLAIN ABOUT THE SAME FUCKING PROBLEMS.**

**Comment by TheSatanicAngeI** [comment]
@reflexin  IF YOU ARE SO GOOD AT COMPLAINING YOU MAY ASWELL START A "REAL" CAREER IN CODING SO EVERYTHING WILL BE "PERFECT" AS YOU SEEMS TO KNOW WHAT TO DO SINCE YOU CAN "CODE"

OH SORRY AM I ASKING TOO MUCH ?

DUH YOU ARE TOO LAZY TO MAKE YOUR OWN HACK AS AN EXCUSE ?

FUCK OFF JUST ADMIT THAT YOU CAN'T CODE.

**Comment by TheSatanicAngeI** [comment]
@reflexin  Yes I'm done, have a nice day now :laughing:

**Comment by humphreygaming** [comment]
@TheSatanicAngeI i agree with you

**Comment by humphreygaming** [comment]
This thread was an adventure. People yelled at each other like americans while cussing as much as australians while in a thread and said "have a nice day goodbye" like canadians would in the end. Amazing

**Comment by TheSatanicAngeI** [comment]
@humphreygaming  But I am canadian lol

**Comment by humphreygaming** [comment]
@TheSatanicAngeI *exactly*

**Comment by TheSatanicAngeI** [comment]
@humphreygaming _oh ok_

**Comment by reflexin** [comment]
> @reflexin ALSO YOU ACT AS IF YOU WERE INNOCENT JUST READ YOUR FUCKING ISSUE TITLE "Have the developers abandoned this extension? Is it on its deathbed? [IMPORTANT]"
> 
> > It seems that the freezing error (which happens 75% of the time), which is a quite fatal problem, is being ignored. No efforts are being made to fix the problem by anyone, and that includes the main developer.
> 
> YES IT IS BEING ABANDONED AND YOU KNOW WHY ?
> 
> **ITS A PAIN TO KEEP UPDATED WITH ALL THE SHITTY KIDS AROUND LIKE YOU THAT OPEN 999 ISSUES JUST TO COMPLAIN ABOUT THE SAME FUCKING PROBLEMS.**

Shut the fuck up you triggered 13 year old asskisser. Didn't read a thing you said, so keep crying in all caps LMAO

**Comment by reflexin** [comment]
> @reflexin ALSO YOU ACT AS IF YOU WERE INNOCENT JUST READ YOUR FUCKING ISSUE TITLE "Have the developers abandoned this extension? Is it on its deathbed? [IMPORTANT]"
> 
> > It seems that the freezing error (which happens 75% of the time), which is a quite fatal problem, is being ignored. No efforts are being made to fix the problem by anyone, and that includes the main developer.
> 
> YES IT IS BEING ABANDONED AND YOU KNOW WHY ?
> 
> **ITS A PAIN TO KEEP UPDATED WITH ALL THE SHITTY KIDS AROUND LIKE YOU THAT OPEN 999 ISSUES JUST TO COMPLAIN ABOUT THE SAME FUCKING PROBLEMS.**

Hey genius, maybe if they were fixed people would stop complaining. Now shut the fuck up and do your homework child.
