### ISSUE TITLE
READ THIS IF YOU WANT TO PLAY WITH HACK!!!

### ISSUE THREAD

**Issue by TheSatanicAngeI** [Kalaborative/survivio-plus#339]
### Just fucking quit it. 
**Look, if you really want to hack a io game that bad just make it yourself. Stop complaing about lack of udpates or many issues for something you get free.**

_Some of the people here spent hours infront of a computer screen to code all of this and trust me it wasn't easy_

**You should be thankful that these people took the time to do those hacks and released it free.**

### Also you can just get good like seriously it isn't that hard
**Making complaining threads about something that is obvious also doesn't help. If you think you're the first person who made a thread about "freezing pls fix" change your mind.**

_I'm sick of all those cry baby who thinks everything is free-earned for them. Life doesn't work that way_

### And finally if you REALLY wanted to get rid of that freezing issue you COULD consider LEARNING how to script YOURSELF to HELP out

_Also just imagine...if you worked hundred of hours to make a game that you hoped people would like and then some of those people decided to abuse the system of your game._ **HOW WOULD YOU FEEL ABOUT THAT?!**

I̶ ̶g̶u̶e̶s̶s̶ ̶m̶y̶ ̶t̶h̶r̶e̶a̶d̶ ̶w̶a̶s̶ ̶p̶o̶i̶n̶t̶l̶e̶s̶s̶ ̶t̶o̶o̶ ̶a̶n̶d̶ ̶t̶h̶a̶t̶ ̶i̶t̶'̶s̶ ̶g̶o̶i̶n̶g̶ ̶t̶o̶ ̶b̶e̶ ̶c̶l̶o̶s̶e̶d̶.̶

**Comment by iBLiSSINYT** [comment]
Truth

**Comment by TheSatanicAngeI** [comment]
I'm assuming the last part was the "truth" :laughing:

**Comment by TheSatanicAngeI** [comment]
![2b6a29c9ecc5f90e7d58abb4530c172d](https://user-images.githubusercontent.com/19210871/53610514-37941f00-3b99-11e9-8f59-6bd35a62629b.png)

### I just WON with no HACK, it isn't that HARD

**Comment by ElectricProgramer** [comment]
It really isn't. I play without hacks. But sometimes people just want to make it easier.

**Comment by Dreamoz** [comment]
are you his lawyer or bodyguard ? no ? f*** off then.

for the creators:

thank you for all your hard work. i think you should make this private and start charging for it, i will be your first customer.

**Comment by TheSatanicAngeI** [comment]
@DreamC***oz And what would be your price hmm ?

I'm just pointing out the obvious things going on here like the whole drama about the freezing going on and edgy kids crying cuz they can't use hack. 

Also guess that's pretty much the only thing I could do to contribute somewhat so just fucking deal with it.

**Comment by TesterBoy22** [comment]
I mean I use a cheat that cost $1 for surviv. It's pretty good and doesn't crash. Even blissin is in the discord for it.  If you want I can send you the link to it

**Comment by IceHacks** [comment]
@TheSatanicAngeI SHUT UP FAGGOT! Hacks could boost that 7 kills to 22 easily. Want a link?

**Comment by humphreygaming** [comment]
lmao @TheSatanicAngeI you suck btw, saiga and 7 kills and IHASYOU name

**Comment by reflexin** [comment]
@TheSatanicAngeI Keep sucking the faggot iPiSSING's dick lol what do you think it will achieve? He has 200 subs

**Comment by Dreamoz** [comment]
> I mean I use a cheat that cost $1 for surviv. It's pretty good and doesn't crash. Even blissin is in the discord for it. If you want I can send you the link to it

can you send me a link ? thx

**Comment by TesterBoy22** [comment]
> > I mean I use a cheat that cost $1 for surviv. It's pretty good and doesn't crash. Even blissin is in the discord for it. If you want I can send you the link to it
> 
> can you send me a link ? thx

https://discord.gg/TaY5Esf

**Comment by TheSatanicAngeI** [comment]
> @TheSatanicAngeI SHUT UP FAGGOT! Hacks could boost that 7 kills to 22 easily. Want a link?

Hacks and cheats are itself illegal which mean you aren't really well placed to talk. 

> I mean I use a cheat that cost $1 for surviv. It's pretty good and doesn't crash. Even blissin is in the discord for it. If you want I can send you the link to it

No thanks I don't participate much in hacking activities paying would be a waste.



> lmao @TheSatanicAngeI you suck btw, saiga and 7 kills and IHASYOU name

Yea sure I suck, what you think I'd take my time to get the best game I could out of sheer luck and skills ? Just for you guys ? Nah you aren't worth it. Also I don't know if you noticed that already but...My name is too long for the fucking game so no I don't use my name. I use random names that are popular by now. It's easier than trying to came up with a new name that I won't really use anyways.



> @TheSatanicAngeI Keep sucking the faggot iPiSSING's dick lol what do you think it will achieve? He has 200 subs

Assuming things is commonly known as an insult for lower IQ beings like you. Unfortunately that poor attempt only managed to make me laugh as you mentioned his sub count. Do I look like someone who cares about fucking numbers ? It is literally meaningless. Also it may looks like this to a lower-intelligent being like you but I'm not actually taking his defense. Sure I favorise his situation but it's my own selfish situation that I want to change. I mean maybe I shouldn't have let notifications on after all. Every time someone made a thread I was just looking it up to see if anything new was brought up and I end up with all the times people complaining about things not working rather than helping or trying to change things. It is frustrating. 


### Last words

**I am very happy to see that I am capable of offending so many people with my meaningless existence, thank you guys so much to for caring, it really means a lot to me.**

**Comment by iBLiSSINYT** [comment]
Holy shit the triple toxicity wtf is this

**Comment by humphreygaming** [comment]
**I am very happy to see that I am capable of offending so many people with my meaningless existence, thank you guys so much to for caring, it really means a lot to me.** **_Meaningless existence_** Keep you meaningless existence to yourself then goddamn

**Comment by TesterBoy22** [comment]
> **I am very happy to see that I am capable of offending so many people with my meaningless existence, thank you guys so much to for caring, it really means a lot to me.** **_Meaningless existence_** Keep your meaningless existence to yourself then goddamn

Yeah what he said

**Comment by IceHacks** [comment]
> > **I am very happy to see that I am capable of offending so many people with my meaningless existence, thank you guys so much to for caring, it really means a lot to me.** **_Meaningless existence_** Keep your meaningless existence to yourself then goddamn
> 
> Yeah what he said

What what they said

**Comment by TheSatanicAngeI** [comment]
@humphreygaming @TesterBoy22 @IceHacks 

Obviously this was sarcasm and you guys got fooled by your own stupidity.

Congratulation! I can now see that you're all teaming as fake friends to have some kind of superiority that you can't get alone.
