### ISSUE TITLE
Can someone explain how this hack works and how I can make my own hack?

### ISSUE THREAD

**Issue by Helixable** [Kalaborative/survivio-plus#341]
Can someone make a detailed guide on how to patch this or something by myself?
And explain how it works in the process? I want to contribute to the extension.

**Comment by IceHacks** [comment]
It replaces functions in the game with custom functions. Those custom functions have other things in them, `detectEnemies()` or `aim(x, y)` for example, which read the game data and base what happens on that. It's pretty simple really. You could go more advanced though.

**Comment by humphreygaming** [comment]
@Helixable learn JavaScript. Simple. An then ask Gatorix (Kalaborative), IceHacks, iBLiSSIN, or me for guidance

**Comment by iBLiSSINYT** [comment]
make it point to the enemy
