### ISSUE TITLE
I think I found a solution to the freezing

### ISSUE THREAD

**Issue by littlebukkaroo** [Kalaborative/survivio-plus#345]
I need help with this part so if anyone can help me please do. @notme1560 @Kalaborative @eugene-chen @Zimm1 @

**Comment by zbot473** [comment]
What exactly do you have in mind?

**Comment by zbot473** [comment]
I can help you, join this: https://discord.gg/TaY5Esf

**Comment by littlebukkaroo** [comment]
i found a way to create the extension as if it is just apart of the game

**Comment by littlebukkaroo** [comment]
it more complicated than that but thats basically what it will do

**Comment by iBLiSSINYT** [comment]
confusion
