### ISSUE TITLE
Freezing related to Latency ???

### ISSUE THREAD

**Issue by TheSatanicAngeI** [Kalaborative/survivio-plus#346]
I've been doing like 10 games so far and I notied my latency was below 60 most of the time and I even had youtube open and everything (shitty computer) and I didn't froze once.

**Comment by humphreygaming** [comment]
latency is the basic ping/ms that surviv.io sends and it has mostly nothing to do with freezing. Is your zoom and tree transparency disabled?

**Comment by 1tarko** [comment]
Does anyone have a solution? it's freezing too much

**Comment by humphreygaming** [comment]
@1tarko get a new hack kid, or watch the videos that are in a older post

**Comment by 1tarko** [comment]
@humphreygaming Which old post? Can you explain me in the discord? skillz#1415

**Comment by humphreygaming** [comment]
@1tarko this one is the old post: https://github.com/Kalaborative/survivio-plus/issues/315

Yes, i can further explain my statement. Accept the discord friend request
