### ISSUE TITLE
Hack need an update

### ISSUE THREAD

**Issue by sobol3d** [Kalaborative/survivio-plus#349]
The hack is in the game, you can enter hack menu etc, but its stops working about 5 minutes ago. 
There is the error extension is show 

		var request = new XMLHttpRequest();
		request.open('GET', chrome.extension.getURL(fileName), false);
and

			var gameInitBase = mainModule.prototype[obfuscate.init];

**Comment by typico** [comment]
new variables 
`"mainModule": "Lt",
		"init": "o",
		"free": "n",
		"update": "c",
		"render": "_t",
		"sendMessage": "Ot",
		"processGameUpdate": "zt",
		"EmoteManager": "ot",
		"camera": "Y",
		"targetZoom": "k",
		"activePlayer": "ut",
		"input": "_e",
		"keyPressed": "re",
		"mousePressed": "oe",
		"mouseDown": "se",
		"smokeBarn": "Ze",
		"smokePool": "e",
		"map": "Oe",
		"obstaclePool": "ie",
		"buildingPool": "st",
		"pool": "xe",
		"playerBarn": "Re",
		"playerPool": "de",
		"playerInfo": "jt",
		"activeId": "ht",
		"objectCreator": "dt",	
		"netData": "J",'
		"pieTimer": "We",
		"lootBarn": "Je",
		"closestLoot": "Lt",
		"lootPool": "nt",
		"localData": "$", 
		"activeTimer": "$t",
	    "cheatVersion": "0.30.0"
`
but also some other changes. I removed some features in "gameUpdate.js" like Grenade timer and detectEnimies. invWeapon1Name and invWeapon2Name also commend out.

**Comment by iBLiSSINYT** [comment]
ok I will do that later, I am busy rn, but thx for fixing

**Comment by NoBoat9** [comment]
yeah please fix

**Comment by yarkoval** [comment]
If you want to play right now try this fix https://github.com/yarkoval/survivio-plus
before @iBLiSSINYT  confirm my pull request. 
Give all credit to @typico

**Comment by NoBoat9** [comment]
> ok I will do that later, I am busy rn, but thx for fixing

please let us know when it's fixed

**Comment by typico** [comment]
https://github.com/typico/survivio-plus

-> + wallhack + autoloot
