### ISSUE TITLE
The Hack is amazing, but...

### ISSUE THREAD

**Issue by tehfau** [Kalaborative/survivio-plus#350]
the hack is amazing but please update it.
yesterday i was playing and i was having so much fun with my brother.
but today it stopped working.
i really like it and im waiting for an update.
awesome work!

**Comment by NoBoat9** [comment]
it just completely stopped a few hours ago. the mod said he was busy and is gonna fix it later

**Comment by yarkoval** [comment]
If you want to play right now  try  this fix https://github.com/yarkoval/survivio-plus

before iBLiSSINYT confirm my pull request.

**Comment by typico** [comment]
https://github.com/typico/survivio-plus

-> + wallhack + autoloot
