### ISSUE TITLE
Help Glitched

### ISSUE THREAD

**Issue by corruptx90** [Kalaborative/survivio-plus#351]
When I try to play the game I can open the hack menu and change all the hacks, but when I play new game it does not work then when I go to fix it and this come up

var request = new XMLHttpRequest(); request.open('GET', chrome.extension.getURL(fileName), false);  

then also this

var gameInitBase = mainModule.prototype[obfuscate.init];

I don't know what this means but before a couple of days ago this had not changed and this was working just fine pls help I don't know what is happening maybe create a entire new hack just like this one but with more things like trigger bot, fire bot, auto dodge, this would be amazing but ya pls help.

**Comment by NoBoat9** [comment]
there's a version someone made a couple hours ago that's a quick fix. it only has the aimbot but will do until the regular version gets fixed

**Comment by littlebukkaroo** [comment]
cool

**Comment by typico** [comment]
https://github.com/typico/survivio-plus

-> + wallhack + autoloot

**Comment by NoBoat9** [comment]
> https://github.com/typico/survivio-plus
> 
> -> + wallhack + autoloot

um it doesnt work
