### ISSUE TITLE
Hack stops working after the update in March 2019.... Please help!

### ISSUE THREAD

**Issue by Mxliee** [Kalaborative/survivio-plus#353]
Hey viewers! I just wanted to leave a not and a request to please fix the Surviv.io Hacks. It stopped working for me when the new update called ''Awesome Blossoms'' came out. please reply and leave a new link that could lead to working hacks for Surviv.io. Thank you.

**Comment by RevoltZZ** [comment]
https://github.com/yarkoval/survivio-plus

**Comment by typico** [comment]
https://github.com/typico/survivio-plus

+ wallhack + autoloot
