### ISSUE TITLE
Surviv.io hack not working at all again

### ISSUE THREAD

**Issue by SkarzXR7** [Kalaborative/survivio-plus#356]
Yeah, the hack isn't working no more :v: , the devs are on to this hack like a bunch of dogs I don't think it'll work anymore, oh gooood. Just jk but please fix it ASAP!

Stopped working 09:54 GMT London UK

**Comment by iBLiSSINYT** [comment]
it does work....

**Comment by SkarzXR7** [comment]
Well, every now and then it just stops working for like a few hours, so
yeah keep that in mind.

Thanks though anyways, love your channel xD

Yasser
