### ISSUE TITLE
[Suggest] Automatically find the obfuscated variables

### ISSUE THREAD

**Issue by ALiangLiang** [Kalaborative/survivio-plus#360]
Sometimes the game is updated. Will cause the obfuscated variables to change. So maybe someone can write the code. Automatically find the obfuscated variables we want.

For example
```js
var objectIds = Object.keys(game[obfuscate.objectCreator].idToObj);
```
`idToObj` is a second level property of `game`. So we can traverse every property.
```js
for (let i in game) {
  for (let t in game[i]) {
    if (t === 'idToObj') {
      console.log('"obfuscate.objectCreator" is"', i, '"')
    }
  }
}
//  output:
// "obfuscate.objectCreator" is "ht"
```

**Comment by iBLiSSINYT** [comment]
obviously
