### ISSUE TITLE
Frag grenade timer not working

### ISSUE THREAD

**Issue by Manseband** [Kalaborative/survivio-plus#361]
Timer won't appear on-screen when baking a frag grenade

**Comment by RevoltZZ** [comment]
Time to play without hacks. Hahaha.

**Comment by nebuzaradan** [comment]
Am i missing something? hacks are not working for me at all for like 2 days :)

**Comment by Manseband** [comment]
Update: Cooking a frag grenade will now freeze the game completely, if the frag grenade timer option is on.

**Comment by Tarun430** [comment]
Yes, please fix this so I know the optimal time of when to throw a grenade

**Comment by iBLiSSINYT** [comment]
here's the fix:






When you cook a nade, count in your head. Magic!
