### ISSUE TITLE
UNAUTHORIZED EXTENSION HELP

### ISSUE THREAD

**Issue by Helixable** [Kalaborative/survivio-plus#37]
There is a notif that sais unauthorized extension.

**Comment by pokeabear** [comment]
It's being worked on. Please don't open duplicate issues. 

You may be unfamiliar with how to look at other issues that were raised and read them. If so, please google "Github Help." 

If you have the skills to  contribute, please do! @Kalaborative works hard to keep this together, and as you can see by reading the other issues, he's aware of and working on the issue, for free.
