### ISSUE TITLE
Pathetic..

### ISSUE THREAD

**Issue by RevoltZZ** [Kalaborative/survivio-plus#372]
From what I see, the boy @iBLiSSINYT behaved badly, he will not have gifts this year.

**Comment by iBLiSSINYT** [comment]
I'm too old for that, by the way Santa isn't real he is just your parents. Sorry to ruin Christmas for you this year.

**Comment by RevoltZZ** [comment]
Kids...

**Comment by humphreygaming** [comment]
@RevoltZZ its true, he just ruined christmas for you. That fat santa is probably your obese dad anyways, since its always your real parents

**Comment by RevoltZZ** [comment]
Protect the girlfriend will.

**Comment by RevoltZZ** [comment]
I'm 23 years old and I'm not old enough to believe in Santa Claus, but our friends @humphreygaming @iBLiSSINYT have

**Comment by humphreygaming** [comment]
why are you in a kids hack repository then?

**Comment by iBLiSSINYT** [comment]
absolutely pathetic, you can't even fix the hack. What an absolute dumbass. Why do you need me to do it for you, son?

**Comment by iBLiSSINYT** [comment]
iM 23 yEaRs oLd! Yeah shut the fuck up, you are smart enough to type that you are 2x older than you actually are. Good job.

**Comment by RevoltZZ** [comment]
"I'm too old for that" Kids...
