### ISSUE TITLE
It's not the same extension anymore

### ISSUE THREAD

**Issue by TheFreakOne** [Kalaborative/survivio-plus#38]
Great and tidy code is gone! It's literally PowerOfUniverse's extension copied and pasted now with small changes. Only some images and color differ. There's no longer RMB to aim, configurable zoom by scroll, good menu or advanced aim options. By overall quality has massively dropped. I will stick to the old one for now because it was incomparably better.

**Comment by Kalaborative** [comment]
It's been reverted. I've managed to solve my original dilemma.

**Comment by TheFreakOne** [comment]
Very good decision, thanks for reverting it. I know JS just enough to keep extension updated and tweak some personal stuff but if there were some bigger update to the game I probably wouldn't be able to maintain the original which is great quality stuff. Thanks again!

**Comment by Kalaborative** [comment]
Anytime! Any help is appreciated :)
