### ISSUE TITLE
granade Freezing

### ISSUE THREAD

**Issue by Th3kkk1** [Kalaborative/survivio-plus#381]
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
manifest.1c7b17af.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app.d9c75e2d.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tag.min.js:21 
    tag.min.js 2.1 ✰ SRV ✰      ads by http://www.adinplay.com/     
VM78:1 [dev] Init system logger
VM78:1 [dev] Used 224 / 255 item types
VM78:1 [dev] Used 617 / 65535 map types
23The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. <URL>
VM78:1 [dev] Sound frag_water_01 defined multiple times!
VM78:1 [dev] Sound pan_pickup_01 defined multiple times!
VM78:1 [dev] Load atlas gradient
VM78:1 [dev] Load atlas shared
VM78:1 [dev] Load atlas main
VM78:1 [dev] Loaded texture assets/main-0-100-45aaaeff.png
VM78:1 [dev] Loaded texture assets/gradient-0-100-af98970f.png
VM78:1 [dev] Loaded texture assets/shared-0-100-a9922714.png
VM78:1 [dev] Loaded texture assets/shared-1-100-1ee82f98.png
VM78:1 [dev] Play delay 2679
VM78:1 [dev] Loaded texture assets/shared-2-100-593a17dc.png
VM78:1 [dev] Ping test results
VM78:1 [dev] ----------------------------------------
VM78:1 [dev] region eu zone   fra ping   0.03
VM78:1 [dev] region eu zone   waw ping   0.043
VM78:1 [dev] region na zone   sfo ping   9999
VM78:1 [dev] region na zone   mia ping   9999
VM78:1 [dev] region na zone   nyc ping   9999
VM78:1 [dev] region na zone   chi ping   9999
VM78:1 [dev] region sa zone   sao ping   9999
VM78:1 [dev] region as zone   sgp ping   9999
VM78:1 [dev] region as zone   nrt ping   9999
VM78:1 [dev] region as zone   hkg ping   9999
VM78:1 [dev] region as zone   kor ping   9999
min.html:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
t.a3cloud.net/gx.png?APN=8017145630292275600&google_gid=CAESEH2K4uPK7LEYVkkE_7n8ETk&google_cver=1:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
t.a3cloud.net/gx.png?APN=8017145630292275600&google_gid=CAESEH2K4uPK7LEYVkkE_7n8ETk&google_cver=1:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
match:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
match:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
set:1 Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
set:1 Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
VM78:1 [dev] Joining ws://31.204.128.32:444/play?gameId=eb868020e11a5c5c4a716eb4cca8ba00
gameUpdate.js:343 Uncaught TypeError: game[obfuscate.pieTimer][obfuscate.free] is not a function
    at runTimer (gameUpdate.js:343)
    at r.window.gameFunctions.gameUpdate (gameUpdate.js:677)
    at r.mainModule.(/anonymous function) [as c] (chrome-extension://lilhgmahfkgcmlfpdabgopmfcefhhebf/webpack_override.js:138:37)
    at i.update (<anonymous>:1:1094019)
    at t.emit (<anonymous>:52:92407)
    at t.update (<anonymous>:46:105179)
    at _tick (<anonymous>:46:103362)
min.html:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by yarkoval** [comment]
@Th3kkk1  just turn off frag grenade timer in menu

**Comment by iBLiSSINYT** [comment]
thx for the spam
