### ISSUE TITLE
Focus on target

### ISSUE THREAD

**Issue by nebuzaradan** [Kalaborative/survivio-plus#382]
Hey

The problem is when there are more than 1 enemy in my view range... i have auto aim enabled... and when its "locked" on one target i cant change my target to another.. so sometimes im locked on one target which is on end of my viewsite and another one is punching me with a bare hands :) .. and i cant change target to that closer enemy.. (pointing my mouse on a new target is not working) so ive tried with auto aim restriction but without any luck.. 

So if there is no option to refresh target (except enemy leaves my view range), could You implement to script to be working in "cycles".. like.. when it is locked on target it "refreshes" after 2-3 seconds.. and then is locking on a target where you are aiming.. and so on..

**Comment by iBLiSSINYT** [comment]
did you completely miss the part where you can disable auto aim always on?
