### ISSUE TITLE
iBLiSSiN closes every single issue

### ISSUE THREAD

**Issue by reflexin** [Kalaborative/survivio-plus#383]
Check out the closed issues for this repository. The moderator iBLiSSiN just closes most, if not all issues automatically. He is also super disrespectful and condescending to most users. Just watch how he'll reply to this.

Also, he just uses this to advertise his YT channel. Nothing more.

**Comment by humphreygaming** [comment]
Uhg, i already mentioned this and i dont want it to start up again

**Comment by iBLiSSINYT** [comment]
Do you possess intelligence?

**Comment by RevoltZZ** [comment]
"dO yOu PoSsEsS InTelLiGeNcE"10/10 argument

**Comment by reflexin** [comment]
>Do you possess intelligence?
>Does exactly what I said

LMFAO, predictable af. Shit mod

**Comment by reflexin** [comment]
> "dO yOu PoSsEsS InTelLiGeNcE"10/10 argument

Fr LMAO
