### ISSUE TITLE
iBLiSSiN closes every single issue [STILL NOT FIXED] 

### ISSUE THREAD

**Issue by reflexin** [Kalaborative/survivio-plus#386]
Opening this again because he closed it and the issue hasn't been solved.

Check out the closed issues for this repository. The moderator iBLiSSiN just closes most, if not all issues automatically. He is also super disrespectful and condescending to most users. Just watch how he'll reply to this.

This is how he responded to my previous post:
https://imgur.com/a/m72HUZI

Also, he just uses this to advertise his YT channel. Nothing more.

**Comment by BigQuantumMan** [comment]
Zero profits <=> lack of professionalism

**Comment by iBLiSSINYT** [comment]
imagine complaining about a hack that you receive for free.

wait, I forgot. where does it say you can't advertise youtube channels on github?

Apparently this is an issue, I close every single issue. Please bring up one closed issue that is of importance and is not been stated already.

Man you guys are annoying, make it worse for everyone. Have fun patching your own hack in the next update.
