### ISSUE TITLE
Unusual freezing error which isn't related to the previous freezing problem. I have the specific line where it crashes

### ISSUE THREAD

**Issue by reflexin** [Kalaborative/survivio-plus#388]
Hi, this is not related to the freezing error. It seems to have improved recently, I haven't froze much at all. Pat on the back from me to whoever is responsible for the improvement!

This bug occurs randomly, it happened at the end of the game for me. The game just froze completely. This is the error message: 

`Uncaught TypeError: game[obfuscate.pieTimer][obfuscate.free] is not a function`

It occurs here:

`payload/gameUpdate.js:343 (anonymous function)`

Also I noticed that the extension crashed twice when picking up a FAMAS and reloading it. Don't know why.

**Comment by iBLiSSINYT** [comment]
Think. pieTimer. Timer. What is being timed? Grenades? Hm Grenades, how can I stop this? 

Famas works fine

**Comment by reflexin** [comment]
> Think. pieTimer. Timer. What is being timed? Grenades? Hm Grenades, how can I stop this?
> 
> Famas works fine

Yeah I recall that someone said grenades were causing freezing too. It crashed when I tried to use a grenade as well. It also makes sense that they call it a "pie" because it's circular. 

And just a note for your help are pie timers used for MIRVs too?
