### ISSUE TITLE
New Update + New Weapon

### ISSUE THREAD

**Issue by drogga** [Kalaborative/survivio-plus#390]
As it says above, Surviv is now at 0.7.5 and introduced the PKP Pecheneg.
Of course the hack stopped working, I thought I'd mention the weapon or else the hack gets updated again but omitting the weapon, so it couldn't be fired.

**Comment by BigQuantumMan** [comment]
This new update is a paradise for people who have cheats.

**Comment by pilgrimoflight** [comment]
Is there other good cheat? Cause this one dies every time with update. 

I dont understand, is it that harf to make 2-3  options light cheat ??? Other options are wasted more or less.

I can swear then, game wont crash as often as it do now

**Comment by khvnhtung** [comment]
New updates comes with new weapons which the cheat client hasn't been updated to add new weapon to the list yet so whenver you hold the new weapon on your hand.. You freezes.

**Comment by BigQuantumMan** [comment]
@pilgrimoflight 
Just type on github...

**Comment by BigQuantumMan** [comment]
In the meantime, you can use this:
https://github.com/BigQuantumMan/Surviv.io-Cheat/

**Comment by BigQuantumMan** [comment]
@pilgrimoflight 
While you wait, you can try my version:
https://github.com/BigQuantumMan/Surviv.io-Cheat

**Comment by pilgrimoflight** [comment]
> @pilgrimoflight
> While you wait, you can try my version:
> https://github.com/BigQuantumMan/Surviv.io-Cheat

Cant download - file isnt found((

**Comment by fan02792** [comment]
> @pilgrimoflight
> While you wait, you can try my version:
> https://github.com/BigQuantumMan/Surviv.io-Cheat

Trojan-Downloader.JS.Agent
https://www.virustotal.com/gui/file/eb08c4261119edc4e2c469aa01f9655fa9b82ddc0ab81eac8c2a93ea9bbb09be/detection

**Comment by BigQuantumMan** [comment]
The fact that 1 out of 58 detected something, it does not mean that it is actually a virus ... I had the same problem when downloading eg cheat iceHack.

**Comment by BigQuantumMan** [comment]
That's why there are 58 engines out there that test it, not 1...
Such an effect can be obtained after code obfuscation...

**Comment by BigQuantumMan** [comment]
https://www.virustotal.com/pl/file/554b26b844543d33e3c921a8c98e466867a312a2e9e22ebfaa14cb60e31097d2/analysis/1555434655/

I did not change anything, just re-read the source code. Next time, please learn how code analysis systems work.

**Comment by BigQuantumMan** [comment]
https://www.npmjs.com/package/javascript-obfuscator

**Comment by BigQuantumMan** [comment]
![image](https://user-images.githubusercontent.com/49454024/56232075-3737e080-6080-11e9-81ce-60d6c5c7ec85.png)

**Comment by pilgrimoflight** [comment]
> That's why there are 58 engines out there that test it, not 1...
> Such an effect can be obtained after code obfuscation...

Any thought why the file doesnt exist for me ? Can you  send me .zip to bodikowal@i.ua, please?

**Comment by BigQuantumMan** [comment]
I fixed it, but you could use this button:
![image](https://user-images.githubusercontent.com/49454024/56245804-91e13480-60a0-11e9-8370-cbde402c1111.png)

**Comment by reflexin** [comment]
> @pilgrimoflight
> I fixed it, but you could use this button:
> ![image](https://user-images.githubusercontent.com/49454024/56245804-91e13480-60a0-11e9-8370-cbde402c1111.png)

Just used your new hack, and WELL DONE! It's honestly the best one I've seen so far. Do you have a paypal link that I could donate to?

**Comment by reflexin** [comment]
> @fan02792
> The fact that 1 out of 58 detected something, it does not mean that it is actually a virus ... I had the same problem when downloading eg cheat iceHack.

Just used your new hack, and WELL DONE! It's honestly the best one I've seen so far. Do you have a paypal link that I could donate to?

**Comment by iBLiSSINYT** [comment]
@reflexin 

Please do. We really need you out of here.

**Comment by reflexin** [comment]
> @reflexin
> 
> Please do. We really need you out of here.

Lmao, real professional behavior from a "Collaborator"
