### ISSUE TITLE
AIMBOT PATCHED

### ISSUE THREAD

**Issue by Tarun430** [Kalaborative/survivio-plus#392]
The aimbot was patched on the new update today. I didn't see anyone else post an issue, so I posted it.

**Comment by humphreygaming** [comment]
the
reason
that
its
not
there
IS BECAUSE ITS NOT PATCHED OR HE IS AWARE OF SUCH

**Comment by iBLiSSINYT** [comment]
WAIT, IT GOT PATCHED??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

Not fixing until tomorrow, have a good day
