### ISSUE TITLE
Green Freeze screen 

### ISSUE THREAD

**Issue by pilgrimoflight** [Kalaborative/survivio-plus#396]
Cheat still doesnt work, when starting a new game
![Screenshot_3](https://user-images.githubusercontent.com/44622177/56304776-8268f680-6147-11e9-969e-10ccc23deea1.jpg)

**Comment by iBLiSSINYT** [comment]
![image](https://user-images.githubusercontent.com/42192427/56306017-7a8d6000-610f-11e9-9342-2372fb2de042.png)

**Comment by pilgrimoflight** [comment]
wow it works for you- true magic
And for at least three people it doesnt.
zaebal daun

**Comment by yarkoval** [comment]
Yeah, it's sad that we can't use extension right now. But i understand reasons. Oh,  crowd of stupid assholes who start a more more issues (many of them are identical) and demand to fix everything right now. It's very facking-annoying. Even for me. And i am not @iBLiSSINYT , who voluntarily  and for free (surprise!) maintain this extension for people who even can't appreciate this. Make your own cheat and stop whining!
