### ISSUE TITLE
USE THIS YOU BLIND RETARDS HOLY FUCK USE YOUR EYES

### ISSUE THREAD

**Issue by iBLiSSINYT** [Kalaborative/survivio-plus#398]
[survivio-plus-master.zip](https://github.com/Kalaborative/survivio-plus/files/3091542/survivio-plus-master.zip)

**Comment by Brushfiremage62** [comment]
wow this hacks attracts more retarded people day by day then my fucking school

**Comment by iBLiSSINYT** [comment]
> wow this hacks attracts more retarded people day by day then my fucking school

your school says a lot about you

**Comment by humphreygaming** [comment]
oof
