### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ResonanceNagger** [Kalaborative/survivio-plus#4]
**Edit : Added more suggestions due to the new update**
### Large Sodas
- Add auto door opening/closing
- Add the spread angles to other players' weapons ( possible bullet evasion )
- Add "streamer mode" - make the cheat only visible to the player ( reuke was trying to implement this )
- Add triggerbot 
### Medium Pizzas
- Add air drop tracking via team pings/map indicators
- Add player analysis ( show the names other players' weapons etc )
- Change other players' color when they're using heals/when they're slowed
- Add grenade outlines ( possible grenade evasion )
- Add grenade land prediction
- Make grenades slowly shift in color/size as they're about to explode when thrown
- Add fake lag/lag switch ( possible anti-aim )
### Small Fries
- Make magazine-fed guns shootable while reloading
- Add auto character spin
- Add an option to change the ground texture
- Fix some of the google translated text in the settings **CYKA BLYAT**
### Already Implemented
- Add an option to change the visibility of the wood that contains the axe
- Make semi-auto shotguns and snipers bump-fire 
- Add melee weapons to the auto pickup list

**Comment by Kalaborative** [comment]
Really appreciate these! I'll see what I can do. 😄

**Comment by humphreygaming** [comment]
someone want to change the "Winner winner chicken dinner" to "PIZZA TIME". its possible is it not? @Kalaborative

**Comment by Kalaborative** [comment]
I'm sure it's possible with a little bit of jQuery. 😂 @humphreygaming 

> Make semi-auto shotguns and snipers bump-fire

Which shotguns are these? I could easily implement this one. @ResonanceNagger

**Comment by ResonanceNagger** [comment]
mp220 and m870 @Kalaborative

**Comment by Kalaborative** [comment]
Alright cool thanks :-) btw should we really add bump fire to Mosin Nagant? It has really slow firing rate and reload time.. idk if it would really make a difference for that gun. The others though I have added

**Comment by Kalaborative** [comment]
Wood transparency for the ax weapon should also be fixed now.

**Comment by ResonanceNagger** [comment]
Yeah, the mosin doesn't really need it @Kalaborative

**Comment by humphreygaming** [comment]
the streamer mode is difficult tho

**Comment by silentes** [comment]
@Kalaborative the hack is good, some tips would be autoloot for wooden ax, make a button for switching weapon positions (for example click T to switch 1 slot with 2 slot), and shift should toggle names on and off not just when ur holding it down. Otherwise, good work man really love it.

**Comment by Kalaborative** [comment]
@silentes Thanks. I should be able to figure out how to add wooden ax to auto loot. I'll try to add everything else in the meantime.

**Comment by Kalaborative** [comment]
https://github.com/Kalaborative/survivio-plus/blob/d21c80e8bdd3a86db23306c20c76e6aa7feadb7b/payload/gameUpdate.js#L317

Axe officially added to auto-loot.

**Comment by silentes** [comment]
@Kalaborative not to add pressure or anything, but something that will be godly with this hack would be player damage counters. I dont know if this would be doable, but something to think about down the line.

**Comment by Kalaborative** [comment]
@silentes that would be really cool, actually. I'll add it to the development board 👍

**Comment by Kalaborative** [comment]
Everything has been accounted for, and will keep updates on the project board
