### ISSUE TITLE
Cannot become Woods King

### ISSUE THREAD

**Issue by gstrk** [Kalaborative/survivio-plus#402]
When you kill someone that is currently woods king, you cannot obtain their outfit which allows you to become woods king. It freezes when you try to do so. Everything else is perfect. Well done.

**Comment by Derpitu** [comment]
wait dude how to enable hack plz healp. :(

**Comment by gstrk** [comment]
> wait dude how to enable hack plz healp. :(

https://www.youtube.com/watch?v=HsSX9C6OJDc&t=140s

**Comment by Derpitu** [comment]
thx :)

**Comment by humphreygaming** [comment]
is that my video? why?

**Comment by gstrk** [comment]
> is that my video? why?

yeah it's really helpful

**Comment by humphreygaming** [comment]
cant you just use IBLISSIN's video?

**Comment by iBLiSSINYT** [comment]
Good question...... Below:

Who The Fuck Cares   ?
