### ISSUE TITLE
Frag Grenade Crashes Game on Throw

### ISSUE THREAD

**Issue by KingDarnit** [Kalaborative/survivio-plus#403]
Every time I attempt to throw a frag grenade, it freezes the game instantly. It has happened about 7 times now. Please fix. Thanks!

Edit: Just noticed it also happens with an MIRV.

**Comment by iBLiSSINYT** [comment]
turn off frag timer

**Comment by RevoltZZ** [comment]
https://github.com/BigQuantumMan/Surviv.io-Cheat/issues?q=is%3Aissue+is%3Aclosed
100% no freeze.
