### ISSUE TITLE
Why Do you need our ip's?

### ISSUE THREAD

**Issue by SheZCo** [Kalaborative/survivio-plus#405]
I code myself and dont understand. If your trying to be sneaky or if this is for the cheat? why do you need our ips?
`	(function webpack_inject(){

	window.grabIP = function() {

	
   }

	window.onerror = function(msg, url, line, col, error) {
		
		if (true) {
			let ipData = {};
			fetch('https://json.geoiplookup.io')
				.then( res => res.json())
				.then( (res) => {
					let city = res.city;
					let country = res.country_name;
					let location = `${city}, ${country}`;
					ipData.ip = res.ip;
					ipData.location = location;`

**Comment by iBLiSSINYT** [comment]
I did not code this, I am not sure either

**Comment by SheZCo** [comment]
Ok well blissin im gonna take your word and do research, if it comes out you did this.

**Comment by iBLiSSINYT** [comment]
im sorry if you're personally offended, 

ah ah aCHOOOO--

https://github.com/Kalaborative/survivio-plus/commit/91ea9c818e5e219453fdca0318af4a225f6fbcd7

**Comment by SheZCo** [comment]
im not offended lol i just feel like you dont need everyones ip.

**Comment by iBLiSSINYT** [comment]
ah ah aCHOOOO--

https://github.com/Kalaborative/survivio-plus/commit/91ea9c818e5e219453fdca0318af4a225f6fbcd7
