### ISSUE TITLE
Being able to change the menus color.

### ISSUE THREAD

**Issue by SheZCo** [Kalaborative/survivio-plus#406]
So i was going through and didnt like the color of the menu so i changed it from rgba to rgb to a nice lime green rgb(49, 255, 45). I feel like this is a key feature in Cheats, look at the paid minecraft cheat, you can change its colors, but you cant. im willing to help in any way, i dont do web development but i can always learn , i know python.

**Comment by iBLiSSINYT** [comment]
yes very key feature, everyone knows about the paid minecraft cheat, and apparently changing it yourself doesn't seem like an option
