### ISSUE TITLE
Can you work on this hack instead ?

### ISSUE THREAD

**Issue by TheSatanicAngeI** [Kalaborative/survivio-plus#407]
The github page was closed/banned user. 

the code is cleaner and it doesn't freeze.

https://1drv.ms/u/s!ApdhqmT4yAP7w2tIXCmpBt2cOGSl

https://mega.nz/#!IYVGVQCa!lCYnatXV2CYohaAvza5hwgQfy_42cuWcIWeQ8VE1enY

**Comment by iBLiSSINYT** [comment]
don't want to go there.

**Comment by TheSatanicAngeI** [comment]
@iBLiSSINYT why ?

**Comment by Brushfiremage62** [comment]
because hes a bitch

**Comment by iBLiSSINYT** [comment]
I'm a bitch, okay. Sorry for fixing the hack everytime it is patched.
