### ISSUE TITLE
fix?

### ISSUE THREAD

**Issue by Brushfiremage62** [Kalaborative/survivio-plus#409]
![Screenshot 2019-04-22 at 2 04 36 PM](https://user-images.githubusercontent.com/45979888/56519404-99249a00-6507-11e9-8823-ea9fa298141d.png)

**Comment by iBLiSSINYT** [comment]
Idiot lmao. 

Love how you keep running your mouth but at the same time continue to use it. Can't possibly be older than 12.

**Comment by Brushfiremage62** [comment]
> Idiot lmao.
> 
> Love how you keep running your mouth but at the same time continue to use it. Can't possibly be older than 12.

why you salty all the time, your such a little bitch
plus i dont play with the hack because of the fucking freezing you pussy

**Comment by Brushfiremage62** [comment]
i wont play surviv until theres a better hack

**Comment by iBLiSSINYT** [comment]
>plus i dont play with the hack because of the fucking freezing you pussy

gtfo?
