### ISSUE TITLE
BigQuantumMan, where are you?

### ISSUE THREAD

**Issue by reflexin** [Kalaborative/survivio-plus#411]
I don't know how else to contact you, but you got banned? Or did you delete it?

**Comment by Brushfiremage62** [comment]
same it was the best hack ever

**Comment by iBLiSSINYT** [comment]
Fuck, whoever shut him down, I need to kill them. They brought these two magical leprechauns here.

**Comment by RevoltZZ** [comment]
Sick Brat.

**Comment by iBLiSSINYT** [comment]
three*

**Comment by Brushfiremage62** [comment]
awe does iBiSSINYT need his fucking bottle because his hack is trash

**Comment by iBLiSSINYT** [comment]
lmao then gtfo if its trash, why ur lame ass still in here?

https://www.urbandictionary.com/define.php?term=Loser

**Comment by Brushfiremage62** [comment]
you had to look up what loser meant, and i'm the idiot
plus im waiting for BigquantumMan to come back 
you worthless piece of shit
