### ISSUE TITLE
BigQuantumMan News

### ISSUE THREAD

**Issue by Exerciz** [Kalaborative/survivio-plus#413]
Hello, anyone heard about BigQuantumMan ? 
Any news about him or his hack?

**Comment by Brushfiremage62** [comment]
no and any second now dickhead is about to close this issue

**Comment by iBLiSSINYT** [comment]
because this is the place to discuss.

**Comment by Exerciz** [comment]
@iBLiSSINYT i don't know why the theard distrubs you ? We can just discuss here...
