### ISSUE TITLE
Freezes the game

### ISSUE THREAD

**Issue by 00petar00** [Kalaborative/survivio-plus#42]
For half a second it will freeze the game, i am not sure what is causing this tried using incognito with no other extensions and i still have this issue.

**Comment by mi99cool** [comment]
I'm not having this issue at all. Just punch the air and it start as normal. Also if it's like half a second that's too small of a time for it to effect your game play anyways.

**Comment by 00petar00** [comment]
Yeah too small of a time to affect anything if it only happens once or at start but it happens like every 5 seconds. I should've mentioned this above. It just happens too often and it is quite unplayable.

**Comment by Dyason** [comment]
I get this same issue, it's completely unplayable now. It happened first for me when the code was changed a while ago.

**Comment by mi99cool** [comment]
No idea what could be causing this issue for you, could be lag spikes on the server which happens and nothing can be done about that. Have you tried playing on the other servers. I do not have this issue

**Comment by Dyason** [comment]
Definitely not the server, it only occurs with the extension activated.

**Comment by mi99cool** [comment]
Well go ahead in install the extension on the opera browser and see how it works on that

**Comment by droidmx** [comment]
The extension is not the problem. Cut down on other chrome processes running at the same time, that should decrease lag.

**Comment by Dyason** [comment]
I'll try opera. I did a restart and disabled all other Chrome extensions
but still had the issue.

**Comment by 00petar00** [comment]
Its not a network lag, when i say freeze i mean it which can't be caused by network lag.

Tried it on opera and its the same like google chrome. I have like 60 pages open on google chrome but if it doesn't work on opera with only one tab there, that shouldn't be a problem.

**Comment by Dyason** [comment]
Just tried it on opera, that too has the same problem. Lots of stuttering freezes. Again no other tabs open.

**Comment by Kalaborative** [comment]
It could be the `gameUpdate.js` file that might be logging something or doing something that requires too much work. If it only occurs when in the game. I'll look at it more and see what it could be, I'm not getting any freezing either.

**Comment by Dyason** [comment]
Thanks. It did only occur first after you optimised your code. At that
point I rolled back to the previous version which didn't have the problem.
Not able to do that now since it doesn't function.

**Comment by Kalaborative** [comment]
@Dyason which commit?

**Comment by Surviv23** [comment]
I have the same problem

**Comment by mi99cool** [comment]
If it was a issue with the extension it should effect everyone that has it installed i'm not getting this issue.

**Comment by 00petar00** [comment]
@Kalaborative It works fine now, i don't have any more issues with this. Thanks for all the hard work.
