### ISSUE TITLE
New Ideas

### ISSUE THREAD

**Issue by asianhacks** [Kalaborative/survivio-plus#43]
You could try working with @powerofuniverse, or @w3x731 who also created a surviv hack. They have great ideas there also. but stopped development. If possible could you try implementing their ideas too? 
https://github.com/w3x731/survivIoAim
https://github.com/PowerOfUniverse/Surviv.io-Cheats

**Comment by ALEXXANDRO23** [comment]
it is true his hacks were simpler but they were very good and having the look x15 is somewhat annoying and the auto aim is somewhat confusing although it is good that aiga someone to continue with the project thx

**Comment by Kalaborative** [comment]
From what I've heard, POU has made it very clear he doesn't want to continue with it. So I will have to devise them or someone else can contribute

**Comment by ALEXXANDRO23** [comment]
I would love it, but I have no idea, I can only think that @zbot473 may be able to help you

**Comment by Kalaborative** [comment]
will add ideas on the project board
