### ISSUE TITLE
Aimbot keeps locking on to someone 500 miles away while there's someone next to you

### ISSUE THREAD

**Issue by survivigod** [Kalaborative/survivio-plus#47]
Probably just me but I feel like I've never had problems like this with POU and your old aimbots....

It keeps locking on to someone like half the map away when there's someone next to you shredding you with a MAC-10

**Comment by mi99cool** [comment]
You need to keep an eye on where the crosshair cursor is as the aim will lock on the person closes to the cursor not the one closes to you.

**Comment by Kalaborative** [comment]
I'm working on this. If you're already shooting someone and you want to target someone else, you need to release your mouse before shooting again.

**Comment by reflexin** [comment]
> You need to keep an eye on where the crosshair cursor is as the aim will lock on the person closes to the cursor not the one closes to you.

It stays locked onto them. Even if they are unshootable (covered by a rock or a wall) and another enemy is right in front of you, which causes death.

This most frequently occurs when there are several enemies around.

**Comment by mi99cool** [comment]
as Kalaborative has said above u have to release mouse button and aim to the one u want to shoot and repress the button, this is how the extension has always worked and is good for me.

**Comment by Kalaborative** [comment]
I seem to have implemented faulty variables due to my Python script. I can confirm with "Auto Aim Restriction" enabled, I no longer have this problem. Can @survivigod or @mi99cool confirm?

**Comment by mi99cool** [comment]
I played a few rounds i always have the "Auto Aim Restriction" enabled, the seems to be no issue for it and can confirm i can use the auto aim without issue. 

Thanks Kalaborative

**Comment by Kalaborative** [comment]
okay great, thanks!
