### ISSUE TITLE
Quite a bit of lag

### ISSUE THREAD

**Issue by reloadednfo** [Kalaborative/survivio-plus#48]
While playing with this extension, every few seconds of gameplay there will be some significant lag where the game will freeze for a second or two. This only occurs when using the extension.

**Comment by Kalaborative** [comment]
There's nothing I found logging during gameplay. At this point all I can do is optimize and reduce file size where possible, but "lag" isn't something that can be fixed from an extension standpoint.

**Comment by reloadednfo** [comment]
You can see by this video what I mean. When the extension is enabled (the first half of the video), the video lags behind quite a bit, and this isn't even at it's worst, sometimes its up to a couple seconds behind. But when the extension isn't enabled (second half), it runs just fine, so it's obviously not the game itself or my internet. I also want to note it wasn't always like this as I've used this extension for a few months and it's worked fine, it's something new over the last month or so that's causing the lag.

https://streamable.com/8h4xp
