### ISSUE TITLE
Lots of issues 

### ISSUE THREAD

**Issue by IME9** [Kalaborative/survivio-plus#49]
Ok let's be real this extension is great and all but it cause an incredible amount of lags.

I estimated around 40% more occurence of lag spikes and random freezes since it's launched in-game.

My network connection is fecking 500mb/s that can't be slow lol. 

Proof : https://gyazo.com/b93e671b2e768c7a1cd8f4809c407090

"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."

Stuff : https://gyazo.com/0848d7651adb47270d500599964ee968

More Stuff : https://gyazo.com/974f4fe8832fa91fae4ed7787824ca62

Hope I helped somehow lol

**Comment by IME9** [comment]
Also update the link of the extension in the thing https://gyazo.com/6ca12893b7cbf15e8c1ab7d5e9df3362 

lolthx

**Comment by IME9** [comment]
Whenever you pick a gun it shows a red line (aim range) which is fine BUT if you stay idle it change to...something else that isn't accurate.

Except if I'm lacking knowledge guns don't change aim range when you stay idle lol. 

Fix this kthx @Kalaborative  I :heart:  your projects!

**Comment by Kalaborative** [comment]
The AJAX request isn't really a bug, just a warning.. **I'll look into how to load files async instead**
To the other comment, that's normal. Shooting guns when idle gives more accurate shot then shooting while moving. That's part of the mechanics of the game!

**Comment by Kalaborative** [comment]
For now, I'm going to rollback the team information code, since jQuery is known for being a little slow, I'll also minify some of the files, hopefully that will help

**Comment by IME9** [comment]
Well that answer everything lol 

I've suggested the aiming thing cuz I never noticed a difference from shooting idle than while moving. 

Also I've used powerofuniverse eversion in the past and the aim didn't had that owo.

**Comment by humphreygaming** [comment]
And also, enable keybinds to be enabled. Lets say "SPACE" key as "fire" is not working

**Comment by mi99cool** [comment]
Hi, good suggestions but number 3 shouldn't be used for the right mouse button as i use that to active the auto aim, I don't want the aim to be on constantly, only when it is needed. That's what made the other extensions hard to use and made looting and breaking crates difficult whenever enemy come near you.

Again Kalaborative very nice work on the extension. ❤️

**Comment by ALEXXANDRO23** [comment]
Totally in agreement with you @IME9 , the automatic target is too confusing, it was better when it was more presiso and it was only deactivated / activated with the letter * Z * only for certain cases and the X15 aspect is confused, the X8 was better ....... Outside of that, it is good that someone takes the time for this type of projects :D

**Comment by IME9** [comment]
@ALEXXANDRO23 Totally agreed with your agreement of my message :rofl:

**Comment by IME9** [comment]
> And also, enable keybinds to be enabled. Lets say "SPACE" key as "fire" is not working

Ive not see any hacks that could keybind "SPACE" to shoot for some reasons. I think the game just doesn't give the choice of shooting with "SPACE"

**Comment by Kalaborative** [comment]
> > And also, enable keybinds to be enabled. Lets say "SPACE" key as "fire" is not working
> 
> Ive not see any hacks that could keybind "SPACE" to shoot for some reasons. I think the game just doesn't give the choice of shooting with "SPACE"
> 
> @humphreygaming
Because spacebar's keycode is zero, it think it is `None`

**Comment by Kalaborative** [comment]
> > And also, enable keybinds to be enabled. Lets say "SPACE" key as "fire" is not working
> 
> Ive not see any hacks that could keybind "SPACE" to shoot for some reasons. I think the game just doesn't give the choice of shooting with "SPACE"
> 
> @humphreygaming


Because spacebar's keycode is 0, so it thinks the key is `None`

**Comment by IME9** [comment]
> Because spacebar's keycode is 0, so it thinks the key is `None`

Seems legit

**Comment by Kalaborative** [comment]
> 1. Make the plane shadow visible when it start flying so you know where it will go and make the drop icon permanent or last untill next drop.

I'm not sure what you mean lol

> 2. AutoHeal ????

Will add it to projects

> 3. Switching gun by pressing right button on mouse (pro tip)

This already exists, though you'd have to rebind auto aim to something else
![alt text](https://puu.sh/BB0v0/4486cff928.png "Quick switch")

> 4. Pressing 'T' to switch gun position (pro tip)

Already mentioned in [this issue](https://github.com/Kalaborative/survivio-plus/issues/31) so will also add it projects
 
> 5. Pressing 'E' to use fists (pro tip)

This has been a feature lol 
![alt text](https://puu.sh/BB0zl/108db0747d.png "Equip fists")

> 6. Use a similar aimbot from powerofuniverse (beside being obvious as hacking because of unstable aiming weapon movement it aims really well and almost never miss while the current one have issues with changing target and aiming)

I've found the other aimbot to be not as smooth, but I'll look into what I can take. The reason it won't be so easy is this extension takes net lag into account

**Comment by IME9** [comment]
> > 1. Make the plane shadow visible when it start flying so you know where it will go and make the drop icon permanent or last untill next drop.
> I'm not sure what you mean lol

In powerofuniverse hack you could see on the map the plane arriving to whatever direction it needed not only when it's under you.

Also when the drop icon appears it stayed there untill next drop leaving you not to concern about putting a marker.

**Comment by IME9** [comment]
@Kalaborative  The option to switch weapon in the hack DOESN'T switch gun positions just which gun is chosen.

This is what  I meant make "T" switch weapons AND positions. (for main gun etc not drag with mouse and change manually)

**Comment by IME9** [comment]
https://gyazo.com/b7864fd24c6d64c5bb63ac8a137b30df **...**

The aimbot is the cause of my death 100% of the time I'm getting triggered :rofl: :anger: 

@Kalaborative  Can you make the aimbot change target on mouse or like "right click on target" to change.

OR if you already integrated a value (option) to change how fast it detect ennemies TELL ME PLS 

I can't really stand it I tried messing up with the aimbot options but I don't get how it works (lol)

**Comment by mi99cool** [comment]
so confusing for me this extension is working perfectly for me i have no issue at all, do you have auto aim always on option enabled turn that off then u can auto aim with the right mouse button will holding it down

**Comment by IME9** [comment]
I'm just saying this because I find the default keybinds you put out of what it should be used for like the same feeling of deja vu from a pc game having controller keybinds lol.

**Comment by IME9** [comment]
> so confusing for me this extension is working perfectly for me i have no issue at all, do you have auto aim always on option enabled turn that off then u can auto aim with the right mouse button will holding it down

EDIT : Nope if I keep holding right mouse button for instance when the blue line appears (and having auto aim off but aim with RMB on) it doesn't aim I'm basically just aiming myself.

**Comment by IME9** [comment]
What I meant to ask (cuz im confusing af sorry)

Is that when I get the red circle from auto aim it always take more time than I wished to change target no matter how I mess with the aim settings.

My goal for the auto aim is that when it get on a user and there's someone next to it I can just RMB and then it goes on the closest next user.

Which isn't the case...

**Comment by IME9** [comment]
If your settings works well and you have no of the issues I have mind showing me screenshots of your settings?

That would really help me cuz I think I really messed up :rofl:

**Comment by Kalaborative** [comment]
RIP ![pic](https://puu.sh/BB3Bi/a1ddd51f99.png)

**Comment by IME9** [comment]
How tf is a not public video blocked LOL

**Comment by Kalaborative** [comment]
Maybe @mi99cool can help ya there, I'll start on this again tomorrow morning I've been working on this just about all day lol

**Comment by IME9** [comment]
@Kalaborative  Wait is that my video that is blocked for you?

**Comment by Kalaborative** [comment]
yeah I'm in the US so idk i guess they blocked something

**Comment by humphreygaming** [comment]
oh, i want it to be space so i could play at school on the chromebooks and use custom aim without a mouse @Kalaborative

**Comment by instantjayden** [comment]
> Whenever you pick a gun it shows a red line (aim range) which is fine BUT if you stay idle it change to...something else that isn't accurate.
> 
> Except if I'm lacking knowledge guns don't change aim range when you stay idle lol.
> 
> Fix this kthx @Kalaborative I ❤️ your projects!
It is shooting while running vs shooting while still and taking time to aim
