### ISSUE TITLE
Just a random question

### ISSUE THREAD

**Issue by survivigod** [Kalaborative/survivio-plus#50]
Prolly one of the most useless questions ever but 
1) can I change the icon?
2) if i can, then what are the file sizes for the three png files? (?x?)

thanks, 
survivigod

**Comment by jialeyu** [comment]
You could probably if you keep the file names the same, and I'm pretty sure the size is the file name (128, 48 and 16).

**Comment by Kalaborative** [comment]
@jialeyu is correct, and you can change whatever you want with the extension lol, it's yours to play with 😛
