### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by asianhacks** [Kalaborative/survivio-plus#51]
I know this will be hard but I was wondering if you could do kind of like an incognito mode. The aimbot, open doors, and pick up are all still active but it is discreet. The game looks like the normal game with no aimbot arrows, no transparent trees or anything, the zoom is normal,  and the weird title screens are back to normal. Pretty much it is like hacking but not wanting people to know your hacking I guess?

**Comment by IME9** [comment]
@asianhacks  You can change all transparency need in the hack settings. 

You can also change the zoom yourself with your mouse.

So what your saying is that you want to become rich over youtube by hacking this game while nobody knows and get a lot of views (I'm being sarcastic) 

Yeah same... that's not how it works.

The best you can do is do what I said.

**Comment by Kalaborative** [comment]
Yes, this was the "streamer mode" reuke proposed a long time ago. If it's just a matter of disabling some settings, I could look into it

**Comment by asianhacks** [comment]
pls try it :) thx
