### ISSUE TITLE
Locks onto one player and there is no way of breaking the lock-on

### ISSUE THREAD

**Issue by reflexin** [Kalaborative/survivio-plus#52]
When there are a lot of players around, it locks onto someone and there is no way of breaking it. The person could be inside of a building and there could be someone right next to you but it still would stay locked on to the guy it originally locked onto.

It's a really nice aimbot, better than the other, this is just the only problem. This should be treated as a high-priority issue because it often causes death for the user.

**Comment by Kalaborative** [comment]
What settings are you using?

**Comment by reflexin** [comment]
> Do you have auto aim always on in the setting, turn that off and then u can use the right mouse button to autoaim and depress it to break the lock on and repress to lock on again on to a different person.

I do have auto-aim always on. I'm not sure what you mean by using the right mouse button to autoaim
