### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Dushy** [Kalaborative/survivio-plus#54]
https://github.com/PowerOfUniverse/Surviv.io-Cheats

You should take a look at this repo

There is some interessting features 👍

- Auto open doors
- Switch weapons by right clicking
- Switch to fist by pressing E

**Comment by colkat406** [comment]
I used to use that one and now on this new one i cant switch the guns as fast as before because i cant right click to change weapons

**Comment by Kalaborative** [comment]
To the last two, scroll down this issue for how to accomplish those #49
