### ISSUE TITLE
A New Feature 

### ISSUE THREAD

**Issue by colkat406** [Kalaborative/survivio-plus#55]
Could you plz add so that when you right click you can change weapons because it is so muc more faster and im used to it cause i used to use another cheat that did this also could u include some on the cheats that this guy has done 
https://github.com/PowerOfUniverse/Surviv.io-Cheats
like Auto Dodge and Fast weapon changing
thanks aslo you are the best :))

**Comment by Kalaborative** [comment]
Hi,

There's a bind for switch weapons on the fourth tab of the cheat menu, auto aim is already bound to right mouse click so you could either rebind auto aim or turn on "Always On Mode"

As nice as the other cheat is, the code is obfuscated, making it very hard to understand. I'll try my best to include what I can

hope that helps! 😄

**Comment by mi99cool** [comment]
Hi, Kalaborative pls do not change the mechanism of how the auto aim works I like how it is. I use right mouse to toggle auto aim on and off
