### ISSUE TITLE
More suggestions and update onto my "lot of issues thread"

### ISSUE THREAD

**Issue by TheSatanicAngeI** [Kalaborative/survivio-plus#56]
### New suggestions!

1. Add plane shadow visibility over the mini-map when spawning and add a drop icon time limit to last untill next drop spawn.

2. I found an handy userscript that made some of the guns show a border line over the selection slot with the color of the ammo it use ; I think this could be usefull if you can complete it @Kalaborative. Also automatic guns have the same border but with dots all over it beside straight line. I can't find the link online anymore so here's my backup of it.
[Hello There Im The Gun Color Script.txt](https://github.com/Kalaborative/survivio-plus/files/2421670/Hello.There.Im.The.Gun.Color.Script.txt)

Notice that 2. is probably not working with the same script language so I guess just run it with your main hack could work idk I'm no scripter.

This is what it looks like : https://gyazo.com/b55240ed51b724d9805832d636ea2a08

3. In powerofuniverse cheat there was a "function" when aiming at a user it would show you what this person had in their inventory. And I'm serious about this. If you can find out what function it was and integrate it to your aim bot and add a variable to trigger it that would be awesome. (That sound easier 
 to say than it is to do isn't it :fearful:) 

4. :thinking:  XD

5. Can you find a way to alter the drinking soda or taking pill boost of speed to make it slightly better? This wouldn't be obvious and could be really handy when you need to get somewhere fast or just run away.

### Concerning my issues...

I'm going to re-download the script with all the default things ok :rofl: so what I would appreciate you to do @Kalaborative is basically just send me a list of what you recommend me to put as settings from your own experience over your cheat and what would be best to change to play with a keyboard if for exemple I hate key numbers (which is the case). 

I think that's it for now! 

PS : Well I guess you're busy I don't mind waiting a few years. . .

**Comment by IME9** [comment]
### BUGS

Upon first download and loading the extension as unpacked when arriving on surviv.io the radio plays but no sound come out. . . Sure this is a minor error but NO BUGS ALLOWED :laughing:

**Comment by mi99cool** [comment]
I'm guessing most of you that have raised issues here have migrated from the powerofuniverse extension which no longer is being updated. You have to understand this is not the same extension and you need to get used to how it works (i like this extension thanks to Kalaborative's great work). 

Remember Kalaborative is doing this for free and saying i don't mind waiting for few years is not helpful, he does not have to do this if he does want to so be appreciative.

**Comment by ALEXXANDRO23** [comment]
you're wrong, @mi99coo, the extension of poweruniverse has already been updated a day ago by zboot, the extension of kolavorative is good but generates some delay and is somewhat confusing

**Comment by ALEXXANDRO23** [comment]
@IME9 The poweruniverse extension is already updated by zbot in case you want to download it.

**Comment by mi99cool** [comment]
Not wrong it just someone else has decided to update and fork it so it good so people can decide which they want. Im sticking with this one, nice work done on this one.

**Comment by silentes** [comment]
Seeing what the player has in their inventory is too much work for something not even useful. 

Closing this one
