### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hithere2002** [Kalaborative/survivio-plus#58]
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vendor.cf4f2202.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app.3754e75e.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
webpack_detect.js:100 webpack detect deployed
webpack_detect.js:59 Uncaught TypeError: Cannot set property 'gameData' of undefined
    at Object.modules.(/anonymous function) (chrome-extension://dhjbajnikgblcpeolmhckmejcnjojpod/webpack_detect.js:59:43)
    at n (<anonymous>:1:101)
    at c99e6613 (<anonymous>:1:782668)
    at Object.modules.(/anonymous function) (chrome-extension://dhjbajnikgblcpeolmhckmejcnjojpod/webpack_detect.js:25:4)
    at n (<anonymous>:1:101)
    at window.webpackJsonp (<anonymous>:1:418)
    at _webpackJsonp (webpack_detect.js:96)
    at <anonymous>:1:1
pagead2.googlesyndication.com/pagead/osd.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
webpack_override.js:10 Uncaught TypeError: Cannot read property 'isDetected' of undefined
    at doWork (webpack_override.js:10)
    at webpack_inject (webpack_override.js:86)
    at webpack_override.js:87
contentscript.js:1 Uncaught Error
    at contentscript.js:1
contentscript.js:1 Uncaught Error
    at contentscript.js:1

**Comment by IME9** [comment]
"Adblock or “browser safety” extensions use a set of parameters which defines what will be blocked. In other words, they contain a list of filters which a web page’s URI’s are checked against upon page load. If a particular resource is requested (i.e. https://googlesyndication.com/pagead/js/adsbygoogle.js) and triggers a filter, then that resource will not be displayed to the user and will display the ERR_BLOCKED_BY_CLIENT message in the Chrome Console."

"There are a few ways to debug and solve an ERR_BLOCKED_BY_CLIENT message.

Disable the extension. This is the simplest solution for the visitor of a website. If you choose to want to see the resources which are being block, simply disable the ad blocker extension which is generating the error.
Whitelist the domain. In many extensions that produce this error, you as a user can also whitelist particular domains. Therefore if you trust a domain and don’t want to block any resources, this will also resolve the ERR_BLOCKED_BY_CLIENT error. "

Tho your issue might not be related to adblocker are you using chrome? 

**Did you made sure to load the extension unpacked and with developer mode on?**

**Comment by Kalaborative** [comment]
The ERR_BLOCKED_BY_CLIENT could also stem from the `background.js` which blocks access to any of the normal JS files the game serves, in which case that is normal behavior. 

are you still having this issue? What is your `webpack_override.js` file look like? because it should be `GameData` not `gameData`
