### ISSUE TITLE
Picking up

### ISSUE THREAD

**Issue by IAmAHumanIThink** [Kalaborative/survivio-plus#61]
Can't pick anything up, with or without autoloot on

**Comment by Kalaborative** [comment]
What version is your extension?

**Comment by mi99cool** [comment]
Hi there, I don't know but if you have been changing setting on the key binds you might have messed something up this happened to me and i also couldn't pick anything up.

**Comment by IME9** [comment]
Same I re-used this extension and fixed a few keybinds and everything work fine (I love the semi-detection aimbot thing like I can just aimbot when I feel like it it's less suspicious that way)

**Comment by Kalaborative** [comment]
Try updating the extension to the latest version and check your keybinds in the fourth menu. I can't seem to replicate the issue, hopefully older ones also have a fix as previously mentioned!
