### ISSUE TITLE
The extension is too easily detectable

### ISSUE THREAD

**Issue by IME9** [Kalaborative/survivio-plus#62]
https://gyazo.com/ae68eae10a9668d2471f3713b6cf8a09

**Comment by Kalaborative** [comment]
Are you running the latest version? Otherwise I just need to update.

**Comment by IME9** [comment]
@Kalaborative Well I reinstalled the extension about 2 hours ago you didn't update again did you?

The game is on the same version so I don't know.

I hit refresh and update and it still does the detection issue.

**Comment by IME9** [comment]
https://gyazo.com/cae2695c2a4c06f3e74164444735d4ee

**Comment by IME9** [comment]
sleep time*

**Comment by sobol3d** [comment]
Yes, they do have make some updates, and the recently downloaded patch just stops working.

**Comment by Kalaborative** [comment]
Sorry yes, it was a small change to the game code, update and it should be working now
