### ISSUE TITLE
[Left shift + Mouse wheel] to zoom?

### ISSUE THREAD

**Issue by Pinky574** [Kalaborative/survivio-plus#64]
Idea: Use Left shift+Mouse wheel to zoom???

**Comment by silentes** [comment]
Why?

**Comment by Kalaborative** [comment]
it can't understand key combinations. if you don't play with zoom then you can already change weapons with the mouse wheel, if you do then you'd have to bind changing weapons to something else

**Comment by ArmaanTornow** [comment]
> it can't understand key combinations. if you don't play with zoom then you can already change weapons with the mouse wheel, if you do then you'd have to bind changing weapons to something else

Check out zbot's survivhack he managed to bind the zoom to shift + scroll.
