### ISSUE TITLE
Hack stop workling

### ISSUE THREAD

**Issue by sobol3d** [Kalaborative/survivio-plus#66]
Hello, today the hack is no working, 
in extencion error is typed " 	request.open('GET', chrome.extension.getURL(fileName), false);

but this time it not give the info about unauthorized extencion, it just seems like normal game

**Comment by sobol3d** [comment]
and its also do have error like this

	var gameInitBase = mainModule.prototype[obfuscate.init];

**Comment by Kalaborative** [comment]
fixed, the other thing is just a warning lol
