### ISSUE TITLE
Can't change the keybind for the shooting action

### ISSUE THREAD

**Issue by reflexin** [Kalaborative/survivio-plus#70]
When you change the keybind to shoot it does not successfully change it. Nothing happens, actually.

**Comment by colkat406** [comment]
It might mean that that bind has already been binded to something else. it happened to me as well

**Comment by Kalaborative** [comment]
It's been hardcoded to be `mousedown`. I'm thinking about removing the keyBinds and just using the default game ones because it's too much work to rewrite the old functionality.

**Comment by Kalaborative** [comment]
Ever since the default survivio game introduced their own custom keybinds, this has been a problem. So we'll just have to work with them for now
