### ISSUE TITLE
Can you apply hacks for proxy websites?

### ISSUE THREAD

**Issue by statawesomeguy** [Kalaborative/survivio-plus#76]
So my school blocked the main surviv.io website which the hacks work on, but survivio has a proxy website called thecircleisclosing.com and survivio plus isn't loaded on that website because the extension doesn't recognize the website as surviv.io. Is there any way to apply the hacks to proxy sites? That would be greatly appreciated.

 Other Official surviv.io proxy sites

http://surviv2.io
https://surviv2.io
http://2dbattleroyale.com
https://2dbattleroyale.com
http://2dbattleroyale.org
https://2dbattleroyale.org
http://piearesquared.info
https://piearesquared.info
http://thecircleisclosing.com
https://thecircleisclosing.com

**Comment by Kalaborative** [comment]
I'll add them to the manifest, thanks!

**Comment by Kalaborative** [comment]
Redownload the extension for the changes to take place!
