### ISSUE TITLE
question

### ISSUE THREAD

**Issue by iceyc** [Kalaborative/survivio-plus#77]
hi i noticed you changed "mainModule" from "_t" to "St" just to update.. how did you find the "mainModule" im trying to learn this stuff and am stuck on that part.. lol

**Comment by Kalaborative** [comment]
It's basically console logging `mainModule` and inspecting the code. [Here's a link on how to generally find variables.](https://docs.google.com/document/d/1idtE-KksJlafgGp97jggGjSGZmRAGgVEYAATAugfE2g/edit?usp=sharing)
