### ISSUE TITLE
i think it's blocked

### ISSUE THREAD

**Issue by minipaik07** [Kalaborative/survivio-plus#78]
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vendor.c9de893b.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app.7adcc219.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tag.min.js:17 
    tag.min.js 1.2s ✰ SRV ✰      ads by http://www.adinplay.com/     
api.adinplay.com/libs/aiptag/assets/adsbygoogle.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
as.casalemedia.com/cygnus?s=254295&v=7.2&r=%7B%22id%22%3A%2210a7f877641fea%22%2C%22imp%22%3A%5B%7B%22id%22%3A%222c3f8b6788d4c7%22%2C%22banner%22%3A%7B%22w%22%3A300%2C%22h%22%3A250%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254295%22%2C%22sid%22%3A%22300x250%22%7D%7D%5D%2C%22site%22%3A%7B%22page%22%3A%22http%3A%2F%2Fsurviv.io%2F%22%2C%22ref%22%3A%22%22%7D%2C%22ext%22%3A%7B%22source%22%3A%22prebid%22%7D%7D&ac=j&sd=1&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ib.adnxs.com/ut/v3/prebid:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
hbopenbid.pubmatic.com/translator?source=prebid-client:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
bid.contextweb.com/header/ortb:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
adinplay-d.openx.net/w/1.0/arj?ju=http%3A%2F%2Fsurviv.io%2F&jr=&ch=UTF-8&res=1536x864x24&ifr=false&tz=-540&tws=1536x755&be=1&bc=hb_pb_2.1.4&dddid=09ae6dc8-e125-4da1-9ea1-ea7ad6587329&nocache=1539283427281&aus=300x250&divIds=surviv-io_300x250&auid=540165239&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
imasdk.googleapis.com/js/sdkloader/ima3.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
integrator.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
integrator.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=1519385255558934&correlator=487606687671637&output=json_html&callback=googletag.impl.pubads.callbackProxy1&impl=fif&eid=21061863%2C21061742%2C21062625&vrg=264&guci=2.2.0.0.2.2.0&plat=1%3A32776%2C2%3A16809992&sc=0&sfv=1-0-29&iu=%2F421469808%2Fsurviv.io_300x250&sz=300x250&eri=1&cookie=ID%3Dabd39f29abd22da9%3AT%3D1522560588%3AS%3DALNI_MbQcDv1fDnH36WPL3CJkKtALe8MCw&bc=7&abxe=1&lmt=1539139916&dt=1539283427616&dlt=1539283426625&idt=980&frm=20&biw=1536&bih=755&oid=2&adx=0&ady=0&adk=1289977631&gut=v2&ifi=1&u_tz=540&u_his=2&u_h=864&u_w=1536&u_ah=826&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=5&u_sd=1.25&flash=0&url=http%3A%2F%2Fsurviv.io%2F&dssz=24&icsg=134220479&std=0&vis=1&scr_x=0&scr_y=0&psz=270x-1&msz=270x-1&ga_vid=1028610929.1522156960&ga_sid=1539283428&ga_hid=136204289&fws=4:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tpc.googlesyndication.com/safeframe/1-0-29/html/container.html:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ib.adnxs.com/ut/v3/prebid:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
(index):1 Uncaught SyntaxError: Unexpected identifier
VM85:1 Uncaught TypeError: Cannot read property 'call' of undefined
    at n (<anonymous>:1:101)
    at Object.c99e6613 (<anonymous>:1:788470)
    at n (<anonymous>:1:101)
    at window.webpackJsonp (<anonymous>:1:418)
    at <anonymous>:1:1
adinplay-d.openx.net/w/1.0/arj?ju=http%3A%2F%2Fsurviv.io%2F&jr=&ch=UTF-8&res=1536x864x24&ifr=false&tz=-540&tws=1536x755&be=1&bc=hb_pb_2.1.4&dddid=3db5ab75-5aef-4c31-bef2-d6e81415a00a&nocache=1539283427624&aus=970x90%2C728x90&divIds=surviv-io_728x90&auid=540165244&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
bid.contextweb.com/header/ortb:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
as.casalemedia.com/cygnus?s=254671&v=7.2&r=%7B%22id%22%3A%2217f208b85983eb2%22%2C%22imp%22%3A%5B%7B%22id%22%3A%2218a8e21773d6325%22%2C%22banner%22%3A%7B%22w%22%3A728%2C%22h%22%3A90%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254671%22%2C%22sid%22%3A%22728x90%22%7D%7D%2C%7B%22id%22%3A%22195a868ab9d5016%22%2C%22banner%22%3A%7B%22w%22%3A970%2C%22h%22%3A90%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254671%22%2C%22sid%22%3A%22970x90%22%7D%7D%5D%2C%22site%22%3A%7B%22page%22%3A%22http%3A%2F%2Fsurviv.io%2F%22%2C%22ref%22%3A%22%22%7D%2C%22ext%22%3A%7B%22source%22%3A%22prebid%22%7D%7D&ac=j&sd=1&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
hbopenbid.pubmatic.com/translator?source=prebid-client:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=1519385255558934&correlator=487606687671637&output=json_html&callback=googletag.impl.pubads.callbackProxy1&impl=fif&eid=21061863%2C21061742%2C21062625&vrg=264&guci=2.2.0.0.2.2.0&plat=1%3A32776%2C2%3A16809992&sc=0&sfv=1-0-29&iu=%2F421469808%2Fsurviv.io_300x250&sz=300x250&eri=1&cookie=ID%3Dabd39f29abd22da9%3AT%3D1522560588%3AS%3DALNI_MbQcDv1fDnH36WPL3CJkKtALe8MCw&bc=7&abxe=1&lmt=1539139916&dt=1539283427616&dlt=1539283426625&idt=980&frm=20&biw=1536&bih=755&oid=2&adx=0&ady=0&adk=1289977631&gut=v2&ifi=1&u_tz=540&u_his=2&u_h=864&u_w=1536&u_ah=826&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=5&u_sd=1.25&flash=0&url=http%3A%2F%2Fsurviv.io%2F&dssz=24&icsg=134220479&std=0&vis=1&scr_x=0&scr_y=0&psz=270x-1&msz=270x-1&ga_vid=1028610929.1522156960&ga_sid=1539283428&ga_hid=136204289&fws=4:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=1519385255558934&correlator=4283802404526971&output=json_html&callback=googletag.impl.pubads.callbackProxy2&impl=fif&eid=21061863%2C21061742%2C21062625&vrg=264&guci=2.2.0.0.2.2.0&plat=1%3A32776%2C2%3A16809992&sc=0&sfv=1-0-29&iu=%2F421469808%2Fsurviv.io_728x90&sz=970x90%7C728x90&eri=1&cookie=ID%3Dabd39f29abd22da9%3AT%3D1522560588%3AS%3DALNI_MbQcDv1fDnH36WPL3CJkKtALe8MCw&bc=7&abxe=1&lmt=1539139916&dt=1539283427771&dlt=1539283426625&idt=980&frm=20&biw=1536&bih=755&oid=2&adx=0&ady=0&adk=129044436&gut=v2&ifi=2&u_tz=540&u_his=2&u_h=864&u_w=1536&u_ah=826&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=5&u_sd=1.25&flash=0&url=http%3A%2F%2Fsurviv.io%2F&dssz=29&icsg=2818575039&std=0&vis=1&scr_x=0&scr_y=0&psz=864x-1&msz=864x-1&ga_vid=1028610929.1522156960&ga_sid=1539283428&ga_hid=136204289&fws=4:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM85:1 Uncaught TypeError: Cannot read property 'call' of undefined
    at n (<anonymous>:1:101)
    at Object.9b5f96fd (<anonymous>:1:475757)
    at n (<anonymous>:1:101)
    at Object.webpack_inject (webpack_override.js:114)
    at n (<anonymous>:1:101)
    at window.webpackJsonp (<anonymous>:1:418)
    at webpack_inject (webpack_override.js:111)
    at webpack_override.js:188
an:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
an:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
an:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
an:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

it seems i cannot connected to server

**Comment by ArmaanTornow** [comment]
The link is to an Ad Delivery company so you must be running an adblock, try removing that.

**Comment by silentes** [comment]
Bruv redownload and those blockings are probably the cheat blocking the ads

**Comment by ArmaanTornow** [comment]
> Bruv redownload and those blockings are probably the cheat blocking the ads

Silentes its V2 Jester from the SG server and I knew U hacked you cuck i shoulda trusted meh gut lol

**Comment by RuanTM** [comment]
var runScript = function(scriptName, callOnLoad) {
	try {
		var e =  document.createElement('script');
		e.src = chrome.extension.getURL(scriptName);
		e.setAttribute('crossorigin', 'anonymous');
		(document.head || document.documentElement).appendChild(e);
		e.onload = function() {
			e.parentNode.removeChild(e);
			if(callOnLoad)
				callOnLoad.call(this);
		};
	} catch (e) {}
};

var loadFile = function(fileName) {
	try{
		var request = new XMLHttpRequest();
		request.open('GET', chrome.extension.getURL(fileName), false);
		request.send(null);  
		if (request.status === 200) {  
		  return request.responseText;  
		}
	}
	catch(e) {}
	return "";
};

(function() {
	try {
		var e =  document.createElement("script");
		
		var menuHtml = loadFile('payload/menu.html');
		var helpEnHtml = loadFile('payload/help-en.html');
		var helpRuHtml = loadFile('payload/help-ru.html');
		var counterHtml = loadFile('payload/FPSCounter.html');

		code = "window.tempVars = {" +
			"menuHtml: `" + menuHtml + "`," +
			"helpEnHtml: `" + helpEnHtml + "`," +
			"helpRuHtml: `" + helpRuHtml + "`," +
			"counterHtml: `" + counterHtml + "`," +
			"};";
			
		e.setAttribute('type', 'text/javascript');
		e.setAttribute('crossorigin', 'anonymous');
		e.innerHTML = code;
		
		(document.head || document.documentElement).appendChild(e);
		e.onload = function() {
			e.parentNode.removeChild(e);
		};
	} catch (e) {}
})();

// payload vars
runScript('payload/gameVars.js');
runScript('payload/gameSetting.js');

// payload functions
runScript('payload/gameInit.js');
runScript('payload/gameFree.js');
runScript('payload/gameOverride.js');
runScript('payload/gameUpdate.js');
runScript('payload/gameRender.js');
runScript('payload/pingOverride.js');

window.addEventListener("load", function load(event){
    window.removeEventListener("load", load, false); 
	
	// injection point
	runScript('webpack_override.js');

	// appearance
	runScript('third_party/jquery-3.3.1.min.js',
		() => {
			runScript('payload/menuAppearance.js');
			runScript('payload/documentChange.js');
	});
},false);

**Comment by minipaik07** [comment]
ohh... it works now thanks a lot guys
