### ISSUE TITLE
Can't pick anything up

### ISSUE THREAD

**Issue by IAmAHumanIThink** [Kalaborative/survivio-plus#80]
As the title says, I can't pick anything up. I can without the extension, and I have autoloot off.

**Comment by Kalaborative** [comment]
Could you try opening the console and see what error you're getting? Or send a screenshot of your keybinds (the fourth tab in the cheat menu)

**Comment by IAmAHumanIThink** [comment]
I found it was my keybinds

**Comment by eimonpakzad** [comment]
That help me
