### ISSUE TITLE
i dont know why bumpfire blocks me

### ISSUE THREAD

**Issue by minipaik07** [Kalaborative/survivio-plus#85]
when i turn on the bump fire, it makes me switch gun to automatic guns, so i cannot use my shotgus, rifles etc... whatever semi automatics. also when i use semi automatics with disabled bumpfire, i can't shoot thoes.. i think semi automatic guns are unable to fire. how can i fix it?

**Comment by Kalaborative** [comment]
The bump fire option is currently a bug. Don't play with it off because you won't be able to shoot anything 
All guns should have the bumpfire option so semi-automatics should work

**Comment by minipaik07** [comment]
got it... but when i turn off it, i can shoot semi-automatics also... is it a bug too?

**Comment by Kalaborative** [comment]
I guess not, not sure how lol
