### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Survivioboi** [Kalaborative/survivio-plus#87]
Not much of an issue, but I suggest you add enemy lasers (of course only you would be able to see them unless they have the cheat as well) and make them a different color (Ex: blue or even better custom lasers) also please add a customizer to your laser to fit everyone's favorite color.

**Comment by RuanTM** [comment]
has some config or something I can do to improve the aimbot?

**Comment by Kalaborative** [comment]
By lasers, are you talking about the "enemy lines"? They're actually already blue but I can make a setting for it to change the color.

**Comment by Survivioboi** [comment]
Oh! I prob didn't update.

**Comment by Survivioboi** [comment]
and thanks!

**Comment by Survivioboi** [comment]
Oh no, I was thinking for enemy lasers as to see enemy shot view so pretty much take your laser and bring it to them and make it a color

**Comment by Kalaborative** [comment]
Oh okay, yeah I think I had that in the dev project board (lasersight for enemies). It will be in the making 😄
