### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by window134** [Kalaborative/survivio-plus#89]
When I first installed this, I accidentally changed the 'use bandage' bind to LMB. I've changed it to something random since, but whenever I'm under 75 health and whenever I try to shoot with LMB, it still tries to use the bandage. The new keybind that I set for the bandage doesn't work as well either. Thanks for your effort on this

**Comment by Kalaborative** [comment]
You can reset all your bindings by deleting the "cheat2Setting" entry in your local storage. Hit **F12**, click the **Application** tab, on the left, click "Local Storage" , click "surviv.io" and delete the *cheat2Setting* key

**Comment by window134** [comment]
Do I have to delete the _cheat2Setting_ every time? Thats what it looks like. 

Also any plans on adding alt movement to the arrow keys?

**Comment by RuanTM** [comment]
I'll explain more I do not know if you will understand, like when I enter the hack the focus of it is right, I'm talking about the business of focusing the player closer to the cursor I change the config of the aimbot he buga or know it there he focuses one and so it defocuses the player and focuses on another when it comes out of rendering or I kill it and it's really annoying, if I can help thank you!

**Comment by window134** [comment]
@Kalaborative Any help on this?

**Comment by silentes** [comment]
@window134 our discord server says u dumb cuz u bound lmb to bandage

arrow keys r 4 2 year olds

**Comment by window134** [comment]
No.. bandage used to be lmb, then was changed but it's glitched and still stuck onto lmb.

**Comment by Kalaborative** [comment]
No, it should only have to be removed once

**Comment by window134** [comment]
Still doesn't fix the issue.

**Comment by silentes** [comment]
So if you still haven't fixed this, try unbinding all your keys. Are you sure deleting cheat2setting isn't working? Even so, delete cheat2setting and then reinstall the hack. I really don't know what else you can do.

**Comment by window134** [comment]
yes does not work yes
