### ISSUE TITLE
Is this workable on Firefox?

### ISSUE THREAD

**Issue by IME9** [Kalaborative/survivio-plus#90]
I was just wondering since I wanted to switch to Firefox because of many detailled researchs I made.

1 - Firefox use less ressources (memory) than Chrome.
2 - Firefox loads pages faster than Chrome.
3 - Firefox use less tasks in manager than Chrome.
4 - Firefox as a design that is pretty-looking and doesn't seems to affect performance overall. 

But it's different and I don't really know for extensions how it works. It is not like Chrome basically.

So does it work on Firefox too? If yes, how am I supposed to install the thing?

**Comment by MonsterPlays** [comment]
Firefox is gay and it won't let you install the hack don't use Firefox it's really gay ok thanks bye.

**Comment by Kalaborative** [comment]
You'd have to convert it to a GreaseMonkey script, and Firefox has removed support for loading unpacked extensions.

**Comment by NilsIrl** [comment]
> You'd have to convert it to a GreaseMonkey script, and Firefox has removed support for loading unpacked extensions.

You can add unpacked extensions in Firefox at about:debugging.
